/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TaskSchedulerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_TIMESTAMP_INTERVAL"
      | "addKeeper"
      | "allTaskIds"
      | "createTask"
      | "disableTask"
      | "enableTask"
      | "executeTask"
      | "getBlocksUntilExecutable"
      | "getEligibleTasks"
      | "getTask"
      | "getTaskCount"
      | "getTaskIds"
      | "getTasksForVault"
      | "getTimeUntilExecutable"
      | "isExecutable"
      | "isWhitelistedKeeper"
      | "keeperWhitelistEnabled"
      | "owner"
      | "removeKeeper"
      | "renounceOwnership"
      | "setKeeperWhitelistEnabled"
      | "tasks"
      | "transferOwnership"
      | "updateTask"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "KeeperAdded"
      | "KeeperRemoved"
      | "KeeperWhitelistChanged"
      | "OwnershipTransferred"
      | "TaskCreated"
      | "TaskDisabled"
      | "TaskEnabled"
      | "TaskExecuted"
      | "TaskUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_TIMESTAMP_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allTaskIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disableTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTask",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlocksUntilExecutable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEligibleTasks",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTask", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getTaskCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTasksForVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilExecutable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "keeperWhitelistEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeKeeper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeperWhitelistEnabled",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTask",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_TIMESTAMP_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addKeeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allTaskIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enableTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBlocksUntilExecutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEligibleTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTaskIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTasksForVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilExecutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExecutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keeperWhitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKeeperWhitelistEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateTask", data: BytesLike): Result;
}

export namespace KeeperAddedEvent {
  export type InputTuple = [keeper: AddressLike];
  export type OutputTuple = [keeper: string];
  export interface OutputObject {
    keeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeeperRemovedEvent {
  export type InputTuple = [keeper: AddressLike];
  export type OutputTuple = [keeper: string];
  export interface OutputObject {
    keeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeeperWhitelistChangedEvent {
  export type InputTuple = [enabled: boolean];
  export type OutputTuple = [enabled: boolean];
  export interface OutputObject {
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    vault: AddressLike,
    keyManager: AddressLike,
    triggerType: BigNumberish,
    nextExecution: BigNumberish,
    interval: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    vault: string,
    keyManager: string,
    triggerType: bigint,
    nextExecution: bigint,
    interval: bigint
  ];
  export interface OutputObject {
    taskId: string;
    vault: string;
    keyManager: string;
    triggerType: bigint;
    nextExecution: bigint;
    interval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDisabledEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskEnabledEvent {
  export type InputTuple = [taskId: BytesLike];
  export type OutputTuple = [taskId: string];
  export interface OutputObject {
    taskId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskExecutedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    newNextExecution: BigNumberish,
    executedAt: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    newNextExecution: bigint,
    executedAt: bigint
  ];
  export interface OutputObject {
    taskId: string;
    newNextExecution: bigint;
    executedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskUpdatedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    newNextExecution: BigNumberish,
    newInterval: BigNumberish
  ];
  export type OutputTuple = [
    taskId: string,
    newNextExecution: bigint,
    newInterval: bigint
  ];
  export interface OutputObject {
    taskId: string;
    newNextExecution: bigint;
    newInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskScheduler extends BaseContract {
  connect(runner?: ContractRunner | null): TaskScheduler;
  waitForDeployment(): Promise<this>;

  interface: TaskSchedulerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_TIMESTAMP_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  addKeeper: TypedContractMethod<[keeper: AddressLike], [void], "nonpayable">;

  allTaskIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  createTask: TypedContractMethod<
    [
      taskId: BytesLike,
      vault: AddressLike,
      keyManager: AddressLike,
      executeCalldata: BytesLike,
      triggerType: BigNumberish,
      nextExecution: BigNumberish,
      interval: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  disableTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  enableTask: TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;

  executeTask: TypedContractMethod<
    [taskId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  getBlocksUntilExecutable: TypedContractMethod<
    [taskId: BytesLike],
    [bigint],
    "view"
  >;

  getEligibleTasks: TypedContractMethod<[], [string[]], "view">;

  getTask: TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, bigint] & {
        vault: string;
        keyManager: string;
        executeCalldata: string;
        triggerType: bigint;
        nextExecution: bigint;
        interval: bigint;
        enabled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getTaskCount: TypedContractMethod<[], [bigint], "view">;

  getTaskIds: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getTasksForVault: TypedContractMethod<
    [vault: AddressLike],
    [string[]],
    "view"
  >;

  getTimeUntilExecutable: TypedContractMethod<
    [taskId: BytesLike],
    [bigint],
    "view"
  >;

  isExecutable: TypedContractMethod<[taskId: BytesLike], [boolean], "view">;

  isWhitelistedKeeper: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  keeperWhitelistEnabled: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeKeeper: TypedContractMethod<
    [keeper: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setKeeperWhitelistEnabled: TypedContractMethod<
    [enabled: boolean],
    [void],
    "nonpayable"
  >;

  tasks: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, bigint] & {
        vault: string;
        keyManager: string;
        executeCalldata: string;
        triggerType: bigint;
        nextExecution: bigint;
        interval: bigint;
        enabled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTask: TypedContractMethod<
    [
      taskId: BytesLike,
      newNextExecution: BigNumberish,
      newInterval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_TIMESTAMP_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addKeeper"
  ): TypedContractMethod<[keeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allTaskIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      vault: AddressLike,
      keyManager: AddressLike,
      executeCalldata: BytesLike,
      triggerType: BigNumberish,
      nextExecution: BigNumberish,
      interval: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableTask"
  ): TypedContractMethod<[taskId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTask"
  ): TypedContractMethod<[taskId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getBlocksUntilExecutable"
  ): TypedContractMethod<[taskId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEligibleTasks"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, bigint] & {
        vault: string;
        keyManager: string;
        executeCalldata: string;
        triggerType: bigint;
        nextExecution: bigint;
        interval: bigint;
        enabled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTaskIds"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTasksForVault"
  ): TypedContractMethod<[vault: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTimeUntilExecutable"
  ): TypedContractMethod<[taskId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isExecutable"
  ): TypedContractMethod<[taskId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelistedKeeper"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "keeperWhitelistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeKeeper"
  ): TypedContractMethod<[keeper: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKeeperWhitelistEnabled"
  ): TypedContractMethod<[enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean, bigint] & {
        vault: string;
        keyManager: string;
        executeCalldata: string;
        triggerType: bigint;
        nextExecution: bigint;
        interval: bigint;
        enabled: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTask"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      newNextExecution: BigNumberish,
      newInterval: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "KeeperAdded"
  ): TypedContractEvent<
    KeeperAddedEvent.InputTuple,
    KeeperAddedEvent.OutputTuple,
    KeeperAddedEvent.OutputObject
  >;
  getEvent(
    key: "KeeperRemoved"
  ): TypedContractEvent<
    KeeperRemovedEvent.InputTuple,
    KeeperRemovedEvent.OutputTuple,
    KeeperRemovedEvent.OutputObject
  >;
  getEvent(
    key: "KeeperWhitelistChanged"
  ): TypedContractEvent<
    KeeperWhitelistChangedEvent.InputTuple,
    KeeperWhitelistChangedEvent.OutputTuple,
    KeeperWhitelistChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDisabled"
  ): TypedContractEvent<
    TaskDisabledEvent.InputTuple,
    TaskDisabledEvent.OutputTuple,
    TaskDisabledEvent.OutputObject
  >;
  getEvent(
    key: "TaskEnabled"
  ): TypedContractEvent<
    TaskEnabledEvent.InputTuple,
    TaskEnabledEvent.OutputTuple,
    TaskEnabledEvent.OutputObject
  >;
  getEvent(
    key: "TaskExecuted"
  ): TypedContractEvent<
    TaskExecutedEvent.InputTuple,
    TaskExecutedEvent.OutputTuple,
    TaskExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TaskUpdated"
  ): TypedContractEvent<
    TaskUpdatedEvent.InputTuple,
    TaskUpdatedEvent.OutputTuple,
    TaskUpdatedEvent.OutputObject
  >;

  filters: {
    "KeeperAdded(address)": TypedContractEvent<
      KeeperAddedEvent.InputTuple,
      KeeperAddedEvent.OutputTuple,
      KeeperAddedEvent.OutputObject
    >;
    KeeperAdded: TypedContractEvent<
      KeeperAddedEvent.InputTuple,
      KeeperAddedEvent.OutputTuple,
      KeeperAddedEvent.OutputObject
    >;

    "KeeperRemoved(address)": TypedContractEvent<
      KeeperRemovedEvent.InputTuple,
      KeeperRemovedEvent.OutputTuple,
      KeeperRemovedEvent.OutputObject
    >;
    KeeperRemoved: TypedContractEvent<
      KeeperRemovedEvent.InputTuple,
      KeeperRemovedEvent.OutputTuple,
      KeeperRemovedEvent.OutputObject
    >;

    "KeeperWhitelistChanged(bool)": TypedContractEvent<
      KeeperWhitelistChangedEvent.InputTuple,
      KeeperWhitelistChangedEvent.OutputTuple,
      KeeperWhitelistChangedEvent.OutputObject
    >;
    KeeperWhitelistChanged: TypedContractEvent<
      KeeperWhitelistChangedEvent.InputTuple,
      KeeperWhitelistChangedEvent.OutputTuple,
      KeeperWhitelistChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskCreated(bytes32,address,address,uint8,uint256,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDisabled(bytes32)": TypedContractEvent<
      TaskDisabledEvent.InputTuple,
      TaskDisabledEvent.OutputTuple,
      TaskDisabledEvent.OutputObject
    >;
    TaskDisabled: TypedContractEvent<
      TaskDisabledEvent.InputTuple,
      TaskDisabledEvent.OutputTuple,
      TaskDisabledEvent.OutputObject
    >;

    "TaskEnabled(bytes32)": TypedContractEvent<
      TaskEnabledEvent.InputTuple,
      TaskEnabledEvent.OutputTuple,
      TaskEnabledEvent.OutputObject
    >;
    TaskEnabled: TypedContractEvent<
      TaskEnabledEvent.InputTuple,
      TaskEnabledEvent.OutputTuple,
      TaskEnabledEvent.OutputObject
    >;

    "TaskExecuted(bytes32,uint256,uint256)": TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;
    TaskExecuted: TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;

    "TaskUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
    TaskUpdated: TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
  };
}
