/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentVaultRegistry {
  export type DeployParamsStruct = {
    budget: BigNumberish;
    period: BigNumberish;
    budgetToken: AddressLike;
    expiration: BigNumberish;
    agents: AddressLike[];
    agentBudgets: BigNumberish[];
    merchants: AddressLike[];
    label: string;
  };

  export type DeployParamsStructOutput = [
    budget: bigint,
    period: bigint,
    budgetToken: string,
    expiration: bigint,
    agents: string[],
    agentBudgets: bigint[],
    merchants: string[],
    label: string
  ] & {
    budget: bigint;
    period: bigint;
    budgetToken: string;
    expiration: bigint;
    agents: string[];
    agentBudgets: bigint[];
    merchants: string[];
    label: string;
  };

  export type VaultRecordStruct = {
    safe: AddressLike;
    keyManager: AddressLike;
    policyEngine: AddressLike;
    label: string;
  };

  export type VaultRecordStructOutput = [
    safe: string,
    keyManager: string,
    policyEngine: string,
    label: string
  ] & { safe: string; keyManager: string; policyEngine: string; label: string };
}

export interface AgentVaultRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedCallers"
      | "deployVault"
      | "deployVaultOnBehalf"
      | "getKeyManager"
      | "getPolicyEngine"
      | "getVaults"
      | "owner"
      | "renounceOwnership"
      | "safeToKeyManager"
      | "safeToPolicyEngine"
      | "setAuthorizedCaller"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallerAuthorizationChanged"
      | "OwnershipTransferred"
      | "VaultDeployed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployVault",
    values: [AgentVaultRegistry.DeployParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "deployVaultOnBehalf",
    values: [AddressLike, AgentVaultRegistry.DeployParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getKeyManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicyEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeToKeyManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "safeToPolicyEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployVaultOnBehalf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getKeyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPolicyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVaults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeToKeyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeToPolicyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CallerAuthorizationChangedEvent {
  export type InputTuple = [caller: AddressLike, authorized: boolean];
  export type OutputTuple = [caller: string, authorized: boolean];
  export interface OutputObject {
    caller: string;
    authorized: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultDeployedEvent {
  export type InputTuple = [
    owner: AddressLike,
    safe: AddressLike,
    keyManager: AddressLike,
    policyEngine: AddressLike,
    label: string,
    chainId: BigNumberish
  ];
  export type OutputTuple = [
    owner: string,
    safe: string,
    keyManager: string,
    policyEngine: string,
    label: string,
    chainId: bigint
  ];
  export interface OutputObject {
    owner: string;
    safe: string;
    keyManager: string;
    policyEngine: string;
    label: string;
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentVaultRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentVaultRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentVaultRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  deployVault: TypedContractMethod<
    [p: AgentVaultRegistry.DeployParamsStruct],
    [AgentVaultRegistry.VaultRecordStructOutput],
    "nonpayable"
  >;

  deployVaultOnBehalf: TypedContractMethod<
    [owner: AddressLike, p: AgentVaultRegistry.DeployParamsStruct],
    [AgentVaultRegistry.VaultRecordStructOutput],
    "nonpayable"
  >;

  getKeyManager: TypedContractMethod<[safe: AddressLike], [string], "view">;

  getPolicyEngine: TypedContractMethod<[safe: AddressLike], [string], "view">;

  getVaults: TypedContractMethod<
    [owner: AddressLike],
    [AgentVaultRegistry.VaultRecordStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  safeToKeyManager: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  safeToPolicyEngine: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  setAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deployVault"
  ): TypedContractMethod<
    [p: AgentVaultRegistry.DeployParamsStruct],
    [AgentVaultRegistry.VaultRecordStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployVaultOnBehalf"
  ): TypedContractMethod<
    [owner: AddressLike, p: AgentVaultRegistry.DeployParamsStruct],
    [AgentVaultRegistry.VaultRecordStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getKeyManager"
  ): TypedContractMethod<[safe: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPolicyEngine"
  ): TypedContractMethod<[safe: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVaults"
  ): TypedContractMethod<
    [owner: AddressLike],
    [AgentVaultRegistry.VaultRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safeToKeyManager"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "safeToPolicyEngine"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedCaller"
  ): TypedContractMethod<
    [caller: AddressLike, authorized: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CallerAuthorizationChanged"
  ): TypedContractEvent<
    CallerAuthorizationChangedEvent.InputTuple,
    CallerAuthorizationChangedEvent.OutputTuple,
    CallerAuthorizationChangedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VaultDeployed"
  ): TypedContractEvent<
    VaultDeployedEvent.InputTuple,
    VaultDeployedEvent.OutputTuple,
    VaultDeployedEvent.OutputObject
  >;

  filters: {
    "CallerAuthorizationChanged(address,bool)": TypedContractEvent<
      CallerAuthorizationChangedEvent.InputTuple,
      CallerAuthorizationChangedEvent.OutputTuple,
      CallerAuthorizationChangedEvent.OutputObject
    >;
    CallerAuthorizationChanged: TypedContractEvent<
      CallerAuthorizationChangedEvent.InputTuple,
      CallerAuthorizationChangedEvent.OutputTuple,
      CallerAuthorizationChangedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VaultDeployed(address,address,address,address,string,uint256)": TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
    VaultDeployed: TypedContractEvent<
      VaultDeployedEvent.InputTuple,
      VaultDeployedEvent.OutputTuple,
      VaultDeployedEvent.OutputObject
    >;
  };
}
