/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MerchantRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "getName" | "isRegistered" | "merchantNames" | "register"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MerchantRegistered" | "MerchantUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getName",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "register", values: [string]): string;

  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
}

export namespace MerchantRegisteredEvent {
  export type InputTuple = [merchant: AddressLike, name: string];
  export type OutputTuple = [merchant: string, name: string];
  export interface OutputObject {
    merchant: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantUpdatedEvent {
  export type InputTuple = [merchant: AddressLike, name: string];
  export type OutputTuple = [merchant: string, name: string];
  export interface OutputObject {
    merchant: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MerchantRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): MerchantRegistry;
  waitForDeployment(): Promise<this>;

  interface: MerchantRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getName: TypedContractMethod<[merchant: AddressLike], [string], "view">;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  merchantNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  register: TypedContractMethod<[name: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getName"
  ): TypedContractMethod<[merchant: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merchantNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[name: string], [void], "nonpayable">;

  getEvent(
    key: "MerchantRegistered"
  ): TypedContractEvent<
    MerchantRegisteredEvent.InputTuple,
    MerchantRegisteredEvent.OutputTuple,
    MerchantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "MerchantUpdated"
  ): TypedContractEvent<
    MerchantUpdatedEvent.InputTuple,
    MerchantUpdatedEvent.OutputTuple,
    MerchantUpdatedEvent.OutputObject
  >;

  filters: {
    "MerchantRegistered(address,string)": TypedContractEvent<
      MerchantRegisteredEvent.InputTuple,
      MerchantRegisteredEvent.OutputTuple,
      MerchantRegisteredEvent.OutputObject
    >;
    MerchantRegistered: TypedContractEvent<
      MerchantRegisteredEvent.InputTuple,
      MerchantRegisteredEvent.OutputTuple,
      MerchantRegisteredEvent.OutputObject
    >;

    "MerchantUpdated(address,string)": TypedContractEvent<
      MerchantUpdatedEvent.InputTuple,
      MerchantUpdatedEvent.OutputTuple,
      MerchantUpdatedEvent.OutputObject
    >;
    MerchantUpdated: TypedContractEvent<
      MerchantUpdatedEvent.InputTuple,
      MerchantUpdatedEvent.OutputTuple,
      MerchantUpdatedEvent.OutputObject
    >;
  };
}
