/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PolicyEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_POLICIES"
      | "addPolicy"
      | "getPolicies"
      | "isPolicy"
      | "owner"
      | "policies"
      | "removePolicy"
      | "renounceOwnership"
      | "safe"
      | "simulateExecution"
      | "simulationActive"
      | "transferOwnership"
      | "validate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutionBlocked"
      | "OwnershipTransferred"
      | "PolicyAdded"
      | "PolicyRemoved"
      | "Validated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_POLICIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "safe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "simulateExecution",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "simulationActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_POLICIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "safe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "simulateExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simulationActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;
}

export namespace ExecutionBlockedEvent {
  export type InputTuple = [
    agent: AddressLike,
    policy: AddressLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    agent: string,
    policy: string,
    token: string,
    to: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    agent: string;
    policy: string;
    token: string;
    to: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyAddedEvent {
  export type InputTuple = [policy: AddressLike];
  export type OutputTuple = [policy: string];
  export interface OutputObject {
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyRemovedEvent {
  export type InputTuple = [index: BigNumberish, policy: AddressLike];
  export type OutputTuple = [index: bigint, policy: string];
  export interface OutputObject {
    index: bigint;
    policy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    token: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    agent: string;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyEngine extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyEngine;
  waitForDeployment(): Promise<this>;

  interface: PolicyEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_POLICIES: TypedContractMethod<[], [bigint], "view">;

  addPolicy: TypedContractMethod<[policy: AddressLike], [void], "nonpayable">;

  getPolicies: TypedContractMethod<[], [string[]], "view">;

  isPolicy: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  removePolicy: TypedContractMethod<
    [index: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  safe: TypedContractMethod<[], [string], "view">;

  simulateExecution: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [[string, string] & { blockingPolicy: string; reason: string }],
    "nonpayable"
  >;

  simulationActive: TypedContractMethod<[], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validate: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_POLICIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addPolicy"
  ): TypedContractMethod<[policy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPolicies"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isPolicy"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removePolicy"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "safe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "simulateExecution"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [[string, string] & { blockingPolicy: string; reason: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "simulationActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validate"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExecutionBlocked"
  ): TypedContractEvent<
    ExecutionBlockedEvent.InputTuple,
    ExecutionBlockedEvent.OutputTuple,
    ExecutionBlockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyAdded"
  ): TypedContractEvent<
    PolicyAddedEvent.InputTuple,
    PolicyAddedEvent.OutputTuple,
    PolicyAddedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyRemoved"
  ): TypedContractEvent<
    PolicyRemovedEvent.InputTuple,
    PolicyRemovedEvent.OutputTuple,
    PolicyRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Validated"
  ): TypedContractEvent<
    ValidatedEvent.InputTuple,
    ValidatedEvent.OutputTuple,
    ValidatedEvent.OutputObject
  >;

  filters: {
    "ExecutionBlocked(address,address,address,address,uint256,string)": TypedContractEvent<
      ExecutionBlockedEvent.InputTuple,
      ExecutionBlockedEvent.OutputTuple,
      ExecutionBlockedEvent.OutputObject
    >;
    ExecutionBlocked: TypedContractEvent<
      ExecutionBlockedEvent.InputTuple,
      ExecutionBlockedEvent.OutputTuple,
      ExecutionBlockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyAdded(address)": TypedContractEvent<
      PolicyAddedEvent.InputTuple,
      PolicyAddedEvent.OutputTuple,
      PolicyAddedEvent.OutputObject
    >;
    PolicyAdded: TypedContractEvent<
      PolicyAddedEvent.InputTuple,
      PolicyAddedEvent.OutputTuple,
      PolicyAddedEvent.OutputObject
    >;

    "PolicyRemoved(uint256,address)": TypedContractEvent<
      PolicyRemovedEvent.InputTuple,
      PolicyRemovedEvent.OutputTuple,
      PolicyRemovedEvent.OutputObject
    >;
    PolicyRemoved: TypedContractEvent<
      PolicyRemovedEvent.InputTuple,
      PolicyRemovedEvent.OutputTuple,
      PolicyRemovedEvent.OutputObject
    >;

    "Validated(address,address,address,uint256)": TypedContractEvent<
      ValidatedEvent.InputTuple,
      ValidatedEvent.OutputTuple,
      ValidatedEvent.OutputObject
    >;
    Validated: TypedContractEvent<
      ValidatedEvent.InputTuple,
      ValidatedEvent.OutputTuple,
      ValidatedEvent.OutputObject
    >;
  };
}
