/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISharedBudgetPool,
  ISharedBudgetPoolInterface,
} from "../../../../contracts/policies/SharedBudgetPolicy.sol/ISharedBudgetPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "vault",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "recordSpend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISharedBudgetPool__factory {
  static readonly abi = _abi;
  static createInterface(): ISharedBudgetPoolInterface {
    return new Interface(_abi) as ISharedBudgetPoolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISharedBudgetPool {
    return new Contract(address, _abi, runner) as unknown as ISharedBudgetPool;
  }
}
