/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILSP14Ownable2Step } from "./ILSP14Ownable2Step";
export type { LSP14Ownable2Step } from "./LSP14Ownable2Step";
