/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ILSP25ExecuteRelayCallInterface extends Interface {
  getFunction(
    nameOrSignature: "executeRelayCall" | "executeRelayCallBatch" | "getNonce"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeRelayCall",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeRelayCallBatch",
    values: [
      BytesLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getNonce",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeRelayCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRelayCallBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
}

export interface ILSP25ExecuteRelayCall extends BaseContract {
  connect(runner?: ContractRunner | null): ILSP25ExecuteRelayCall;
  waitForDeployment(): Promise<this>;

  interface: ILSP25ExecuteRelayCallInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeRelayCall: TypedContractMethod<
    [
      signature: BytesLike,
      nonce: BigNumberish,
      validityTimestamps: BigNumberish,
      payload: BytesLike
    ],
    [string],
    "payable"
  >;

  executeRelayCallBatch: TypedContractMethod<
    [
      signatures: BytesLike[],
      nonces: BigNumberish[],
      validityTimestamps: BigNumberish[],
      values: BigNumberish[],
      payloads: BytesLike[]
    ],
    [string[]],
    "payable"
  >;

  getNonce: TypedContractMethod<
    [from: AddressLike, channelId: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeRelayCall"
  ): TypedContractMethod<
    [
      signature: BytesLike,
      nonce: BigNumberish,
      validityTimestamps: BigNumberish,
      payload: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeRelayCallBatch"
  ): TypedContractMethod<
    [
      signatures: BytesLike[],
      nonces: BigNumberish[],
      validityTimestamps: BigNumberish[],
      values: BigNumberish[],
      payloads: BytesLike[]
    ],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getNonce"
  ): TypedContractMethod<
    [from: AddressLike, channelId: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
