/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyEngine,
  IPolicyEngineInterface,
} from "../../../contracts/AgentSafe.sol/IPolicyEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "validate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPolicyEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyEngineInterface {
    return new Interface(_abi) as IPolicyEngineInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyEngine {
    return new Contract(address, _abi, runner) as unknown as IPolicyEngine;
  }
}
