/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface BudgetPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "budget"
      | "budgetToken"
      | "owner"
      | "ownerSetBudget"
      | "period"
      | "periodDuration"
      | "periodStart"
      | "policyEngine"
      | "renounceOwnership"
      | "spent"
      | "transferOwnership"
      | "validate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BudgetSpent"
      | "BudgetUpdated"
      | "OwnershipTransferred"
      | "PeriodReset"
  ): EventFragment;

  encodeFunctionData(functionFragment: "budget", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "budgetToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerSetBudget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "period", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "periodDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "periodStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "spent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "budget", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "budgetToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "period", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "periodDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "periodStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;
}

export namespace BudgetSpentEvent {
  export type InputTuple = [
    agent: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    newSpent: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    token: string,
    amount: bigint,
    newSpent: bigint
  ];
  export interface OutputObject {
    agent: string;
    token: string;
    amount: bigint;
    newSpent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetUpdatedEvent {
  export type InputTuple = [newBudget: BigNumberish];
  export type OutputTuple = [newBudget: bigint];
  export interface OutputObject {
    newBudget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeriodResetEvent {
  export type InputTuple = [newPeriodStart: BigNumberish];
  export type OutputTuple = [newPeriodStart: bigint];
  export interface OutputObject {
    newPeriodStart: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BudgetPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): BudgetPolicy;
  waitForDeployment(): Promise<this>;

  interface: BudgetPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  budget: TypedContractMethod<[], [bigint], "view">;

  budgetToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerSetBudget: TypedContractMethod<
    [_budget: BigNumberish],
    [void],
    "nonpayable"
  >;

  period: TypedContractMethod<[], [bigint], "view">;

  periodDuration: TypedContractMethod<[], [bigint], "view">;

  periodStart: TypedContractMethod<[], [bigint], "view">;

  policyEngine: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  spent: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validate: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      arg2: AddressLike,
      amount: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "budget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "budgetToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerSetBudget"
  ): TypedContractMethod<[_budget: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "period"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "periodDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "periodStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "spent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validate"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      arg2: AddressLike,
      amount: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BudgetSpent"
  ): TypedContractEvent<
    BudgetSpentEvent.InputTuple,
    BudgetSpentEvent.OutputTuple,
    BudgetSpentEvent.OutputObject
  >;
  getEvent(
    key: "BudgetUpdated"
  ): TypedContractEvent<
    BudgetUpdatedEvent.InputTuple,
    BudgetUpdatedEvent.OutputTuple,
    BudgetUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PeriodReset"
  ): TypedContractEvent<
    PeriodResetEvent.InputTuple,
    PeriodResetEvent.OutputTuple,
    PeriodResetEvent.OutputObject
  >;

  filters: {
    "BudgetSpent(address,address,uint256,uint256)": TypedContractEvent<
      BudgetSpentEvent.InputTuple,
      BudgetSpentEvent.OutputTuple,
      BudgetSpentEvent.OutputObject
    >;
    BudgetSpent: TypedContractEvent<
      BudgetSpentEvent.InputTuple,
      BudgetSpentEvent.OutputTuple,
      BudgetSpentEvent.OutputObject
    >;

    "BudgetUpdated(uint256)": TypedContractEvent<
      BudgetUpdatedEvent.InputTuple,
      BudgetUpdatedEvent.OutputTuple,
      BudgetUpdatedEvent.OutputObject
    >;
    BudgetUpdated: TypedContractEvent<
      BudgetUpdatedEvent.InputTuple,
      BudgetUpdatedEvent.OutputTuple,
      BudgetUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PeriodReset(uint256)": TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;
    PeriodReset: TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;
  };
}
