/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MerchantPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_MERCHANTS"
      | "addMerchants"
      | "getMerchants"
      | "isMerchant"
      | "merchantList"
      | "owner"
      | "policyEngine"
      | "removeMerchant"
      | "renounceOwnership"
      | "transferOwnership"
      | "validate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MerchantAdded"
      | "MerchantRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_MERCHANTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMerchants",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerchants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeMerchant",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_MERCHANTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addMerchants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerchants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isMerchant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merchantList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;
}

export namespace MerchantAddedEvent {
  export type InputTuple = [merchant: AddressLike];
  export type OutputTuple = [merchant: string];
  export interface OutputObject {
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerchantRemovedEvent {
  export type InputTuple = [merchant: AddressLike];
  export type OutputTuple = [merchant: string];
  export interface OutputObject {
    merchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MerchantPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): MerchantPolicy;
  waitForDeployment(): Promise<this>;

  interface: MerchantPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_MERCHANTS: TypedContractMethod<[], [bigint], "view">;

  addMerchants: TypedContractMethod<
    [merchants: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getMerchants: TypedContractMethod<[], [string[]], "view">;

  isMerchant: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  merchantList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policyEngine: TypedContractMethod<[], [string], "view">;

  removeMerchant: TypedContractMethod<
    [merchant: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validate: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      to: AddressLike,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_MERCHANTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addMerchants"
  ): TypedContractMethod<[merchants: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMerchants"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isMerchant"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merchantList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeMerchant"
  ): TypedContractMethod<[merchant: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validate"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      to: AddressLike,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "view"
  >;

  getEvent(
    key: "MerchantAdded"
  ): TypedContractEvent<
    MerchantAddedEvent.InputTuple,
    MerchantAddedEvent.OutputTuple,
    MerchantAddedEvent.OutputObject
  >;
  getEvent(
    key: "MerchantRemoved"
  ): TypedContractEvent<
    MerchantRemovedEvent.InputTuple,
    MerchantRemovedEvent.OutputTuple,
    MerchantRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "MerchantAdded(address)": TypedContractEvent<
      MerchantAddedEvent.InputTuple,
      MerchantAddedEvent.OutputTuple,
      MerchantAddedEvent.OutputObject
    >;
    MerchantAdded: TypedContractEvent<
      MerchantAddedEvent.InputTuple,
      MerchantAddedEvent.OutputTuple,
      MerchantAddedEvent.OutputObject
    >;

    "MerchantRemoved(address)": TypedContractEvent<
      MerchantRemovedEvent.InputTuple,
      MerchantRemovedEvent.OutputTuple,
      MerchantRemovedEvent.OutputObject
    >;
    MerchantRemoved: TypedContractEvent<
      MerchantRemovedEvent.InputTuple,
      MerchantRemovedEvent.OutputTuple,
      MerchantRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
