/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SharedBudgetPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CHILD_POOLS"
      | "MAX_POOL_DEPTH"
      | "MAX_VAULTS_PER_POOL"
      | "addChildPool"
      | "addVaultToPool"
      | "authorizedPolicy"
      | "createPool"
      | "getPool"
      | "getPoolRemaining"
      | "getVaultAncestry"
      | "getVaultPool"
      | "owner"
      | "pools"
      | "recordSpend"
      | "renounceOwnership"
      | "setAuthorizedPolicy"
      | "transferOwnership"
      | "vaultToPool"
      | "wouldExceedBudget"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuthorizedPolicyChanged"
      | "BudgetSpent"
      | "ChildPoolAdded"
      | "OwnershipTransferred"
      | "PeriodReset"
      | "PoolCreated"
      | "VaultAddedToPool"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CHILD_POOLS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_POOL_DEPTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VAULTS_PER_POOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChildPool",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addVaultToPool",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedPolicy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "getPool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPoolRemaining",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultAncestry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "recordSpend",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultToPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wouldExceedBudget",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CHILD_POOLS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_POOL_DEPTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VAULTS_PER_POOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addChildPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addVaultToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultAncestry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wouldExceedBudget",
    data: BytesLike
  ): Result;
}

export namespace AuthorizedPolicyChangedEvent {
  export type InputTuple = [oldPolicy: AddressLike, newPolicy: AddressLike];
  export type OutputTuple = [oldPolicy: string, newPolicy: string];
  export interface OutputObject {
    oldPolicy: string;
    newPolicy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetSpentEvent {
  export type InputTuple = [
    poolId: BytesLike,
    vault: AddressLike,
    amount: BigNumberish,
    newSpent: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    vault: string,
    amount: bigint,
    newSpent: bigint
  ];
  export interface OutputObject {
    poolId: string;
    vault: string;
    amount: bigint;
    newSpent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChildPoolAddedEvent {
  export type InputTuple = [childPool: BytesLike, parentPool: BytesLike];
  export type OutputTuple = [childPool: string, parentPool: string];
  export interface OutputObject {
    childPool: string;
    parentPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeriodResetEvent {
  export type InputTuple = [poolId: BytesLike, newPeriodStart: BigNumberish];
  export type OutputTuple = [poolId: string, newPeriodStart: bigint];
  export interface OutputObject {
    poolId: string;
    newPeriodStart: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    parentPool: BytesLike,
    budget: BigNumberish,
    period: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    parentPool: string,
    budget: bigint,
    period: bigint
  ];
  export interface OutputObject {
    poolId: string;
    parentPool: string;
    budget: bigint;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultAddedToPoolEvent {
  export type InputTuple = [vault: AddressLike, poolId: BytesLike];
  export type OutputTuple = [vault: string, poolId: string];
  export interface OutputObject {
    vault: string;
    poolId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SharedBudgetPool extends BaseContract {
  connect(runner?: ContractRunner | null): SharedBudgetPool;
  waitForDeployment(): Promise<this>;

  interface: SharedBudgetPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CHILD_POOLS: TypedContractMethod<[], [bigint], "view">;

  MAX_POOL_DEPTH: TypedContractMethod<[], [bigint], "view">;

  MAX_VAULTS_PER_POOL: TypedContractMethod<[], [bigint], "view">;

  addChildPool: TypedContractMethod<
    [parentId: BytesLike, childId: BytesLike],
    [void],
    "nonpayable"
  >;

  addVaultToPool: TypedContractMethod<
    [poolId: BytesLike, vault: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedPolicy: TypedContractMethod<[], [string], "view">;

  createPool: TypedContractMethod<
    [
      poolId: BytesLike,
      parentPool: BytesLike,
      budget: BigNumberish,
      _period: BigNumberish,
      vaults: AddressLike[],
      childPoolIds: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getPool: TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, string[], string[]] & {
        budget: bigint;
        spent: bigint;
        periodStart: bigint;
        period: bigint;
        parentPool: string;
        vaultMembers: string[];
        childPools: string[];
      }
    ],
    "view"
  >;

  getPoolRemaining: TypedContractMethod<[poolId: BytesLike], [bigint], "view">;

  getVaultAncestry: TypedContractMethod<
    [vault: AddressLike],
    [string[]],
    "view"
  >;

  getVaultPool: TypedContractMethod<[vault: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, boolean] & {
        budget: bigint;
        spent: bigint;
        periodStart: bigint;
        period: bigint;
        parentPool: string;
        initialized: boolean;
      }
    ],
    "view"
  >;

  recordSpend: TypedContractMethod<
    [vault: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuthorizedPolicy: TypedContractMethod<
    [_authorizedPolicy: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vaultToPool: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  wouldExceedBudget: TypedContractMethod<
    [vault: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CHILD_POOLS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_POOL_DEPTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VAULTS_PER_POOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addChildPool"
  ): TypedContractMethod<
    [parentId: BytesLike, childId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addVaultToPool"
  ): TypedContractMethod<
    [poolId: BytesLike, vault: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedPolicy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      poolId: BytesLike,
      parentPool: BytesLike,
      budget: BigNumberish,
      _period: BigNumberish,
      vaults: AddressLike[],
      childPoolIds: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [poolId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, string[], string[]] & {
        budget: bigint;
        spent: bigint;
        periodStart: bigint;
        period: bigint;
        parentPool: string;
        vaultMembers: string[];
        childPools: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolRemaining"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultAncestry"
  ): TypedContractMethod<[vault: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVaultPool"
  ): TypedContractMethod<[vault: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, boolean] & {
        budget: bigint;
        spent: bigint;
        periodStart: bigint;
        period: bigint;
        parentPool: string;
        initialized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordSpend"
  ): TypedContractMethod<
    [vault: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedPolicy"
  ): TypedContractMethod<
    [_authorizedPolicy: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultToPool"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "wouldExceedBudget"
  ): TypedContractMethod<
    [vault: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "AuthorizedPolicyChanged"
  ): TypedContractEvent<
    AuthorizedPolicyChangedEvent.InputTuple,
    AuthorizedPolicyChangedEvent.OutputTuple,
    AuthorizedPolicyChangedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetSpent"
  ): TypedContractEvent<
    BudgetSpentEvent.InputTuple,
    BudgetSpentEvent.OutputTuple,
    BudgetSpentEvent.OutputObject
  >;
  getEvent(
    key: "ChildPoolAdded"
  ): TypedContractEvent<
    ChildPoolAddedEvent.InputTuple,
    ChildPoolAddedEvent.OutputTuple,
    ChildPoolAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PeriodReset"
  ): TypedContractEvent<
    PeriodResetEvent.InputTuple,
    PeriodResetEvent.OutputTuple,
    PeriodResetEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultAddedToPool"
  ): TypedContractEvent<
    VaultAddedToPoolEvent.InputTuple,
    VaultAddedToPoolEvent.OutputTuple,
    VaultAddedToPoolEvent.OutputObject
  >;

  filters: {
    "AuthorizedPolicyChanged(address,address)": TypedContractEvent<
      AuthorizedPolicyChangedEvent.InputTuple,
      AuthorizedPolicyChangedEvent.OutputTuple,
      AuthorizedPolicyChangedEvent.OutputObject
    >;
    AuthorizedPolicyChanged: TypedContractEvent<
      AuthorizedPolicyChangedEvent.InputTuple,
      AuthorizedPolicyChangedEvent.OutputTuple,
      AuthorizedPolicyChangedEvent.OutputObject
    >;

    "BudgetSpent(bytes32,address,uint256,uint256)": TypedContractEvent<
      BudgetSpentEvent.InputTuple,
      BudgetSpentEvent.OutputTuple,
      BudgetSpentEvent.OutputObject
    >;
    BudgetSpent: TypedContractEvent<
      BudgetSpentEvent.InputTuple,
      BudgetSpentEvent.OutputTuple,
      BudgetSpentEvent.OutputObject
    >;

    "ChildPoolAdded(bytes32,bytes32)": TypedContractEvent<
      ChildPoolAddedEvent.InputTuple,
      ChildPoolAddedEvent.OutputTuple,
      ChildPoolAddedEvent.OutputObject
    >;
    ChildPoolAdded: TypedContractEvent<
      ChildPoolAddedEvent.InputTuple,
      ChildPoolAddedEvent.OutputTuple,
      ChildPoolAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PeriodReset(bytes32,uint256)": TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;
    PeriodReset: TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;

    "PoolCreated(bytes32,bytes32,uint256,uint8)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "VaultAddedToPool(address,bytes32)": TypedContractEvent<
      VaultAddedToPoolEvent.InputTuple,
      VaultAddedToPoolEvent.OutputTuple,
      VaultAddedToPoolEvent.OutputObject
    >;
    VaultAddedToPool: TypedContractEvent<
      VaultAddedToPoolEvent.InputTuple,
      VaultAddedToPoolEvent.OutputTuple,
      VaultAddedToPoolEvent.OutputObject
    >;
  };
}
