/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface VaultDirectoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_SAFE_BATCH"
      | "allVaults"
      | "getAllVaults"
      | "getVault"
      | "getVaultCount"
      | "getVaultLabel"
      | "getVaultPool"
      | "getVaults"
      | "isVaultRegistered"
      | "owner"
      | "registerVault"
      | "renounceOwnership"
      | "transferOwnership"
      | "unregisterVault"
      | "updatePoolLink"
      | "updateVaultLabel"
      | "vaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PoolLinkUpdated"
      | "VaultLabelUpdated"
      | "VaultRegistered"
      | "VaultUnregistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_SAFE_BATCH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allVaults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllVaults",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultLabel",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaults",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerVault",
    values: [AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePoolLink",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVaultLabel",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "vaults", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "MAX_SAFE_BATCH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVaults", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVaultRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePoolLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVaultLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaults", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolLinkUpdatedEvent {
  export type InputTuple = [vault: AddressLike, newPool: BytesLike];
  export type OutputTuple = [vault: string, newPool: string];
  export interface OutputObject {
    vault: string;
    newPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultLabelUpdatedEvent {
  export type InputTuple = [vault: AddressLike, newLabel: string];
  export type OutputTuple = [vault: string, newLabel: string];
  export interface OutputObject {
    vault: string;
    newLabel: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultRegisteredEvent {
  export type InputTuple = [
    vault: AddressLike,
    label: string,
    linkedPool: BytesLike
  ];
  export type OutputTuple = [vault: string, label: string, linkedPool: string];
  export interface OutputObject {
    vault: string;
    label: string;
    linkedPool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnregisteredEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VaultDirectory extends BaseContract {
  connect(runner?: ContractRunner | null): VaultDirectory;
  waitForDeployment(): Promise<this>;

  interface: VaultDirectoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_SAFE_BATCH: TypedContractMethod<[], [bigint], "view">;

  allVaults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getAllVaults: TypedContractMethod<[], [string[]], "view">;

  getVault: TypedContractMethod<
    [vault: AddressLike],
    [
      [string, string, string, boolean] & {
        vaultAddr: string;
        label: string;
        linkedPool: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  getVaultCount: TypedContractMethod<[], [bigint], "view">;

  getVaultLabel: TypedContractMethod<[vault: AddressLike], [string], "view">;

  getVaultPool: TypedContractMethod<[vault: AddressLike], [string], "view">;

  getVaults: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  isVaultRegistered: TypedContractMethod<
    [vault: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerVault: TypedContractMethod<
    [vault: AddressLike, label: string, linkedPool: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unregisterVault: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePoolLink: TypedContractMethod<
    [vault: AddressLike, newPool: BytesLike],
    [void],
    "nonpayable"
  >;

  updateVaultLabel: TypedContractMethod<
    [vault: AddressLike, newLabel: string],
    [void],
    "nonpayable"
  >;

  vaults: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        vault: string;
        label: string;
        linkedPool: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_SAFE_BATCH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allVaults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAllVaults"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [vault: AddressLike],
    [
      [string, string, string, boolean] & {
        vaultAddr: string;
        label: string;
        linkedPool: string;
        registered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVaultLabel"
  ): TypedContractMethod<[vault: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVaultPool"
  ): TypedContractMethod<[vault: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVaults"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVaultRegistered"
  ): TypedContractMethod<[vault: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerVault"
  ): TypedContractMethod<
    [vault: AddressLike, label: string, linkedPool: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterVault"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePoolLink"
  ): TypedContractMethod<
    [vault: AddressLike, newPool: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateVaultLabel"
  ): TypedContractMethod<
    [vault: AddressLike, newLabel: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaults"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean] & {
        vault: string;
        label: string;
        linkedPool: string;
        registered: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolLinkUpdated"
  ): TypedContractEvent<
    PoolLinkUpdatedEvent.InputTuple,
    PoolLinkUpdatedEvent.OutputTuple,
    PoolLinkUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultLabelUpdated"
  ): TypedContractEvent<
    VaultLabelUpdatedEvent.InputTuple,
    VaultLabelUpdatedEvent.OutputTuple,
    VaultLabelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultRegistered"
  ): TypedContractEvent<
    VaultRegisteredEvent.InputTuple,
    VaultRegisteredEvent.OutputTuple,
    VaultRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnregistered"
  ): TypedContractEvent<
    VaultUnregisteredEvent.InputTuple,
    VaultUnregisteredEvent.OutputTuple,
    VaultUnregisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolLinkUpdated(address,bytes32)": TypedContractEvent<
      PoolLinkUpdatedEvent.InputTuple,
      PoolLinkUpdatedEvent.OutputTuple,
      PoolLinkUpdatedEvent.OutputObject
    >;
    PoolLinkUpdated: TypedContractEvent<
      PoolLinkUpdatedEvent.InputTuple,
      PoolLinkUpdatedEvent.OutputTuple,
      PoolLinkUpdatedEvent.OutputObject
    >;

    "VaultLabelUpdated(address,string)": TypedContractEvent<
      VaultLabelUpdatedEvent.InputTuple,
      VaultLabelUpdatedEvent.OutputTuple,
      VaultLabelUpdatedEvent.OutputObject
    >;
    VaultLabelUpdated: TypedContractEvent<
      VaultLabelUpdatedEvent.InputTuple,
      VaultLabelUpdatedEvent.OutputTuple,
      VaultLabelUpdatedEvent.OutputObject
    >;

    "VaultRegistered(address,string,bytes32)": TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;
    VaultRegistered: TypedContractEvent<
      VaultRegisteredEvent.InputTuple,
      VaultRegisteredEvent.OutputTuple,
      VaultRegisteredEvent.OutputObject
    >;

    "VaultUnregistered(address)": TypedContractEvent<
      VaultUnregisteredEvent.InputTuple,
      VaultUnregisteredEvent.OutputTuple,
      VaultUnregisteredEvent.OutputObject
    >;
    VaultUnregistered: TypedContractEvent<
      VaultUnregisteredEvent.InputTuple,
      VaultUnregisteredEvent.OutputTuple,
      VaultUnregisteredEvent.OutputObject
    >;
  };
}
