/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ExecutionControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentSafe"
      | "auditHook"
      | "callsInBlock"
      | "executeTokenWithPolicies"
      | "executeWithPolicies"
      | "lastBlockNumber"
      | "maxCallsPerBlock"
      | "owner"
      | "policyEngine"
      | "renounceOwnership"
      | "setAuditHook"
      | "setMaxCallsPerBlock"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditHookFailed"
      | "AuditHookSet"
      | "ExecutionCompleted"
      | "ExecutionStarted"
      | "OwnershipTransferred"
      | "RateLimitUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agentSafe", values?: undefined): string;
  encodeFunctionData(functionFragment: "auditHook", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "callsInBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTokenWithPolicies",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithPolicies",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBlockNumber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxCallsPerBlock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAuditHook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxCallsPerBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentSafe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "auditHook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callsInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTokenWithPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxCallsPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuditHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxCallsPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AuditHookFailedEvent {
  export type InputTuple = [
    hook: AddressLike,
    agent: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    hook: string,
    agent: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    hook: string;
    agent: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditHookSetEvent {
  export type InputTuple = [hook: AddressLike];
  export type OutputTuple = [hook: string];
  export interface OutputObject {
    hook: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionCompletedEvent {
  export type InputTuple = [
    agent: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    paymentType: string
  ];
  export type OutputTuple = [
    agent: string,
    to: string,
    amount: bigint,
    paymentType: string
  ];
  export interface OutputObject {
    agent: string;
    to: string;
    amount: bigint;
    paymentType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionStartedEvent {
  export type InputTuple = [
    agent: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    paymentType: string
  ];
  export type OutputTuple = [
    agent: string,
    to: string,
    amount: bigint,
    paymentType: string
  ];
  export interface OutputObject {
    agent: string;
    to: string;
    amount: bigint;
    paymentType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExecutionController extends BaseContract {
  connect(runner?: ContractRunner | null): ExecutionController;
  waitForDeployment(): Promise<this>;

  interface: ExecutionControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentSafe: TypedContractMethod<[], [string], "view">;

  auditHook: TypedContractMethod<[], [string], "view">;

  callsInBlock: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  executeTokenWithPolicies: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  executeWithPolicies: TypedContractMethod<
    [
      agent: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  lastBlockNumber: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxCallsPerBlock: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policyEngine: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAuditHook: TypedContractMethod<[hook: AddressLike], [void], "nonpayable">;

  setMaxCallsPerBlock: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentSafe"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "auditHook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "callsInBlock"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeTokenWithPolicies"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeWithPolicies"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastBlockNumber"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxCallsPerBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuditHook"
  ): TypedContractMethod<[hook: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxCallsPerBlock"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuditHookFailed"
  ): TypedContractEvent<
    AuditHookFailedEvent.InputTuple,
    AuditHookFailedEvent.OutputTuple,
    AuditHookFailedEvent.OutputObject
  >;
  getEvent(
    key: "AuditHookSet"
  ): TypedContractEvent<
    AuditHookSetEvent.InputTuple,
    AuditHookSetEvent.OutputTuple,
    AuditHookSetEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionCompleted"
  ): TypedContractEvent<
    ExecutionCompletedEvent.InputTuple,
    ExecutionCompletedEvent.OutputTuple,
    ExecutionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionStarted"
  ): TypedContractEvent<
    ExecutionStartedEvent.InputTuple,
    ExecutionStartedEvent.OutputTuple,
    ExecutionStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitUpdated"
  ): TypedContractEvent<
    RateLimitUpdatedEvent.InputTuple,
    RateLimitUpdatedEvent.OutputTuple,
    RateLimitUpdatedEvent.OutputObject
  >;

  filters: {
    "AuditHookFailed(address,address,address,uint256)": TypedContractEvent<
      AuditHookFailedEvent.InputTuple,
      AuditHookFailedEvent.OutputTuple,
      AuditHookFailedEvent.OutputObject
    >;
    AuditHookFailed: TypedContractEvent<
      AuditHookFailedEvent.InputTuple,
      AuditHookFailedEvent.OutputTuple,
      AuditHookFailedEvent.OutputObject
    >;

    "AuditHookSet(address)": TypedContractEvent<
      AuditHookSetEvent.InputTuple,
      AuditHookSetEvent.OutputTuple,
      AuditHookSetEvent.OutputObject
    >;
    AuditHookSet: TypedContractEvent<
      AuditHookSetEvent.InputTuple,
      AuditHookSetEvent.OutputTuple,
      AuditHookSetEvent.OutputObject
    >;

    "ExecutionCompleted(address,address,uint256,string)": TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;
    ExecutionCompleted: TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;

    "ExecutionStarted(address,address,uint256,string)": TypedContractEvent<
      ExecutionStartedEvent.InputTuple,
      ExecutionStartedEvent.OutputTuple,
      ExecutionStartedEvent.OutputObject
    >;
    ExecutionStarted: TypedContractEvent<
      ExecutionStartedEvent.InputTuple,
      ExecutionStartedEvent.OutputTuple,
      ExecutionStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RateLimitUpdated(uint256)": TypedContractEvent<
      RateLimitUpdatedEvent.InputTuple,
      RateLimitUpdatedEvent.OutputTuple,
      RateLimitUpdatedEvent.OutputObject
    >;
    RateLimitUpdated: TypedContractEvent<
      RateLimitUpdatedEvent.InputTuple,
      RateLimitUpdatedEvent.OutputTuple,
      RateLimitUpdatedEvent.OutputObject
    >;
  };
}
