/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IAgentSafeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentExecute"
      | "agentExecuteFor"
      | "agentTransferToken"
      | "agentTransferTokenFor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "agentExecute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentExecuteFor",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentTransferToken",
    values: [AddressLike, AddressLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentTransferTokenFor",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentExecuteFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentTransferToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentTransferTokenFor",
    data: BytesLike
  ): Result;
}

export interface IAgentSafe extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentSafe;
  waitForDeployment(): Promise<this>;

  interface: IAgentSafeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentExecute: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  agentExecuteFor: TypedContractMethod<
    [
      agent: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  agentTransferToken: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  agentTransferTokenFor: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentExecute"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentExecuteFor"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentTransferToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentTransferTokenFor"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
