/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ILSP20CallVerifierInterface extends Interface {
  getFunction(
    nameOrSignature: "lsp20VerifyCall" | "lsp20VerifyCallResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lsp20VerifyCall",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lsp20VerifyCallResult",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "lsp20VerifyCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lsp20VerifyCallResult",
    data: BytesLike
  ): Result;
}

export interface ILSP20CallVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): ILSP20CallVerifier;
  waitForDeployment(): Promise<this>;

  interface: ILSP20CallVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lsp20VerifyCall: TypedContractMethod<
    [
      requestor: AddressLike,
      target: AddressLike,
      caller: AddressLike,
      value: BigNumberish,
      callData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  lsp20VerifyCallResult: TypedContractMethod<
    [callHash: BytesLike, callResult: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lsp20VerifyCall"
  ): TypedContractMethod<
    [
      requestor: AddressLike,
      target: AddressLike,
      caller: AddressLike,
      value: BigNumberish,
      callData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lsp20VerifyCallResult"
  ): TypedContractMethod<
    [callHash: BytesLike, callResult: BytesLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
