/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILSP14Ownable2Step,
  ILSP14Ownable2StepInterface,
} from "../../../../@lukso/lsp14-contracts/contracts/ILSP14Ownable2Step";

const _abi = [
  {
    anonymous: false,
    inputs: [],
    name: "OwnershipRenounced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "RenounceOwnershipStarted",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pendingOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILSP14Ownable2Step__factory {
  static readonly abi = _abi;
  static createInterface(): ILSP14Ownable2StepInterface {
    return new Interface(_abi) as ILSP14Ownable2StepInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILSP14Ownable2Step {
    return new Contract(address, _abi, runner) as unknown as ILSP14Ownable2Step;
  }
}
