/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyEngineSimulation,
  IPolicyEngineSimulationInterface,
} from "../../../../contracts/policies/BudgetPolicy.sol/IPolicyEngineSimulation";

const _abi = [
  {
    inputs: [],
    name: "simulationActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPolicyEngineSimulation__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyEngineSimulationInterface {
    return new Interface(_abi) as IPolicyEngineSimulationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyEngineSimulation {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPolicyEngineSimulation;
  }
}
