/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Version,
  VersionInterface,
} from "../../../../@lukso/lsp6-contracts/contracts/Version";

const _abi = [
  {
    inputs: [],
    name: "VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Version__factory {
  static readonly abi = _abi;
  static createInterface(): VersionInterface {
    return new Interface(_abi) as VersionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Version {
    return new Contract(address, _abi, runner) as unknown as Version;
  }
}
