/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentSafeReentrant,
  IAgentSafeReentrantInterface,
} from "../../../../contracts/mocks/MockReentrantToken.sol/IAgentSafeReentrant";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "allowNonLSP1Recipient",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "tokenData",
        type: "bytes",
      },
    ],
    name: "agentTransferToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentSafeReentrant__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentSafeReentrantInterface {
    return new Interface(_abi) as IAgentSafeReentrantInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentSafeReentrant {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAgentSafeReentrant;
  }
}
