/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RateLimiterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callsInBlock"
      | "checkRateLimit"
      | "enableRateLimitingForVault"
      | "getRemainingCallsInBlock"
      | "lastBlockNumber"
      | "maxCallsPerBlock"
      | "owner"
      | "rateLimitingEnabled"
      | "renounceOwnership"
      | "setMaxCallsPerBlock"
      | "transferOwnership"
      | "wouldExceedRateLimit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxCallsPerBlockUpdated"
      | "OwnershipTransferred"
      | "RateLimitCheckPassed"
      | "RateLimitExceeded"
      | "RateLimitingEnabledForVault"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "callsInBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRateLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableRateLimitingForVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingCallsInBlock",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBlockNumber",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxCallsPerBlock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rateLimitingEnabled",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxCallsPerBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "wouldExceedRateLimit",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "callsInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkRateLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableRateLimitingForVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingCallsInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBlockNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxCallsPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rateLimitingEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxCallsPerBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "wouldExceedRateLimit",
    data: BytesLike
  ): Result;
}

export namespace MaxCallsPerBlockUpdatedEvent {
  export type InputTuple = [newLimit: BigNumberish];
  export type OutputTuple = [newLimit: bigint];
  export interface OutputObject {
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitCheckPassedEvent {
  export type InputTuple = [
    agent: AddressLike,
    blockNumber: BigNumberish,
    callCount: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    blockNumber: bigint,
    callCount: bigint
  ];
  export interface OutputObject {
    agent: string;
    blockNumber: bigint;
    callCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitExceededEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateLimitingEnabledForVaultEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RateLimiter extends BaseContract {
  connect(runner?: ContractRunner | null): RateLimiter;
  waitForDeployment(): Promise<this>;

  interface: RateLimiterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callsInBlock: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  checkRateLimit: TypedContractMethod<
    [agent: AddressLike],
    [[boolean, bigint] & { isAllowed: boolean; currentCallCount: bigint }],
    "nonpayable"
  >;

  enableRateLimitingForVault: TypedContractMethod<
    [vault: AddressLike],
    [void],
    "nonpayable"
  >;

  getRemainingCallsInBlock: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  lastBlockNumber: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxCallsPerBlock: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  rateLimitingEnabled: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaxCallsPerBlock: TypedContractMethod<
    [newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  wouldExceedRateLimit: TypedContractMethod<
    [agent: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callsInBlock"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkRateLimit"
  ): TypedContractMethod<
    [agent: AddressLike],
    [[boolean, bigint] & { isAllowed: boolean; currentCallCount: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enableRateLimitingForVault"
  ): TypedContractMethod<[vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRemainingCallsInBlock"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastBlockNumber"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxCallsPerBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rateLimitingEnabled"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxCallsPerBlock"
  ): TypedContractMethod<[newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "wouldExceedRateLimit"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  getEvent(
    key: "MaxCallsPerBlockUpdated"
  ): TypedContractEvent<
    MaxCallsPerBlockUpdatedEvent.InputTuple,
    MaxCallsPerBlockUpdatedEvent.OutputTuple,
    MaxCallsPerBlockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitCheckPassed"
  ): TypedContractEvent<
    RateLimitCheckPassedEvent.InputTuple,
    RateLimitCheckPassedEvent.OutputTuple,
    RateLimitCheckPassedEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitExceeded"
  ): TypedContractEvent<
    RateLimitExceededEvent.InputTuple,
    RateLimitExceededEvent.OutputTuple,
    RateLimitExceededEvent.OutputObject
  >;
  getEvent(
    key: "RateLimitingEnabledForVault"
  ): TypedContractEvent<
    RateLimitingEnabledForVaultEvent.InputTuple,
    RateLimitingEnabledForVaultEvent.OutputTuple,
    RateLimitingEnabledForVaultEvent.OutputObject
  >;

  filters: {
    "MaxCallsPerBlockUpdated(uint256)": TypedContractEvent<
      MaxCallsPerBlockUpdatedEvent.InputTuple,
      MaxCallsPerBlockUpdatedEvent.OutputTuple,
      MaxCallsPerBlockUpdatedEvent.OutputObject
    >;
    MaxCallsPerBlockUpdated: TypedContractEvent<
      MaxCallsPerBlockUpdatedEvent.InputTuple,
      MaxCallsPerBlockUpdatedEvent.OutputTuple,
      MaxCallsPerBlockUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RateLimitCheckPassed(address,uint256,uint256)": TypedContractEvent<
      RateLimitCheckPassedEvent.InputTuple,
      RateLimitCheckPassedEvent.OutputTuple,
      RateLimitCheckPassedEvent.OutputObject
    >;
    RateLimitCheckPassed: TypedContractEvent<
      RateLimitCheckPassedEvent.InputTuple,
      RateLimitCheckPassedEvent.OutputTuple,
      RateLimitCheckPassedEvent.OutputObject
    >;

    "RateLimitExceeded(address)": TypedContractEvent<
      RateLimitExceededEvent.InputTuple,
      RateLimitExceededEvent.OutputTuple,
      RateLimitExceededEvent.OutputObject
    >;
    RateLimitExceeded: TypedContractEvent<
      RateLimitExceededEvent.InputTuple,
      RateLimitExceededEvent.OutputTuple,
      RateLimitExceededEvent.OutputObject
    >;

    "RateLimitingEnabledForVault(address)": TypedContractEvent<
      RateLimitingEnabledForVaultEvent.InputTuple,
      RateLimitingEnabledForVaultEvent.OutputTuple,
      RateLimitingEnabledForVaultEvent.OutputObject
    >;
    RateLimitingEnabledForVault: TypedContractEvent<
      RateLimitingEnabledForVaultEvent.InputTuple,
      RateLimitingEnabledForVaultEvent.OutputTuple,
      RateLimitingEnabledForVaultEvent.OutputObject
    >;
  };
}
