/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lsp1Contracts from "./lsp1-contracts";
export type { lsp1Contracts };
import type * as lsp14Contracts from "./lsp14-contracts";
export type { lsp14Contracts };
import type * as lsp17ContractextensionContracts from "./lsp17contractextension-contracts";
export type { lsp17ContractextensionContracts };
import type * as lsp20Contracts from "./lsp20-contracts";
export type { lsp20Contracts };
import type * as lsp25Contracts from "./lsp25-contracts";
export type { lsp25Contracts };
import type * as lsp6Contracts from "./lsp6-contracts";
export type { lsp6Contracts };
import type * as lsp9Contracts from "./lsp9-contracts";
export type { lsp9Contracts };
