/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AgentCoordinator {
  export type AgentConfigStruct = {
    isContract: boolean;
    maxGasPerCall: BigNumberish;
    allowedAutomation: boolean;
  };

  export type AgentConfigStructOutput = [
    isContract: boolean,
    maxGasPerCall: bigint,
    allowedAutomation: boolean
  ] & {
    isContract: boolean;
    maxGasPerCall: bigint;
    allowedAutomation: boolean;
  };
}

export interface AgentCoordinatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CAN_PAY"
      | "CAN_REBALANCE"
      | "CAN_SUBSCRIBE"
      | "CAN_TRADE"
      | "CAN_TRANSFER"
      | "CAN_YIELD"
      | "agentRoles"
      | "agents"
      | "assignRole"
      | "canBeAutomated"
      | "getAgentConfig"
      | "getAgentRoles"
      | "getCapabilitiesForRole"
      | "getMaxGasPerCall"
      | "getRoleMembers"
      | "grantCapability"
      | "hasCapability"
      | "hasRole"
      | "isAgentRegistered"
      | "isContractAgent"
      | "owner"
      | "registerAgent"
      | "renounceOwnership"
      | "revokeCapability"
      | "revokeRole"
      | "roleAdmin"
      | "roleCapabilities"
      | "roleMembers"
      | "setAllowedAutomation"
      | "setMaxGasPerCall"
      | "setRoleAdmin"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "CapabilityGranted"
      | "CapabilityRevoked"
      | "OwnershipTransferred"
      | "RoleAdminChanged"
      | "RoleDefinedForAgent"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "CAN_PAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CAN_REBALANCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CAN_SUBSCRIBE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CAN_TRADE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CAN_TRANSFER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CAN_YIELD", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "agentRoles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "assignRole",
    values: [AddressLike, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canBeAutomated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentRoles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCapabilitiesForRole",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxGasPerCall",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleMembers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCapability",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCapability",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgentRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isContractAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCapability",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "roleAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "roleCapabilities",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roleMembers",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedAutomation",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxGasPerCall",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoleAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "CAN_PAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CAN_REBALANCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CAN_SUBSCRIBE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CAN_TRADE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CAN_TRANSFER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "CAN_YIELD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentRoles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canBeAutomated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentRoles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCapabilitiesForRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxGasPerCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAgentRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "roleAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "roleCapabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxGasPerCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    isContract: boolean,
    maxGasPerCall: BigNumberish,
    allowedAutomation: boolean
  ];
  export type OutputTuple = [
    agent: string,
    isContract: boolean,
    maxGasPerCall: bigint,
    allowedAutomation: boolean
  ];
  export interface OutputObject {
    agent: string;
    isContract: boolean;
    maxGasPerCall: bigint;
    allowedAutomation: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilityGrantedEvent {
  export type InputTuple = [agent: AddressLike, capability: BytesLike];
  export type OutputTuple = [agent: string, capability: string];
  export interface OutputObject {
    agent: string;
    capability: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CapabilityRevokedEvent {
  export type InputTuple = [agent: AddressLike, capability: BytesLike];
  export type OutputTuple = [agent: string, capability: string];
  export interface OutputObject {
    agent: string;
    capability: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleDefinedForAgentEvent {
  export type InputTuple = [
    agent: AddressLike,
    role: BytesLike,
    capabilities: BytesLike[]
  ];
  export type OutputTuple = [
    agent: string,
    role: string,
    capabilities: string[]
  ];
  export interface OutputObject {
    agent: string;
    role: string;
    capabilities: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [agent: AddressLike, role: BytesLike];
  export type OutputTuple = [agent: string, role: string];
  export interface OutputObject {
    agent: string;
    role: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentCoordinator extends BaseContract {
  connect(runner?: ContractRunner | null): AgentCoordinator;
  waitForDeployment(): Promise<this>;

  interface: AgentCoordinatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CAN_PAY: TypedContractMethod<[], [string], "view">;

  CAN_REBALANCE: TypedContractMethod<[], [string], "view">;

  CAN_SUBSCRIBE: TypedContractMethod<[], [string], "view">;

  CAN_TRADE: TypedContractMethod<[], [string], "view">;

  CAN_TRANSFER: TypedContractMethod<[], [string], "view">;

  CAN_YIELD: TypedContractMethod<[], [string], "view">;

  agentRoles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, boolean] & {
        isContract: boolean;
        maxGasPerCall: bigint;
        allowedAutomation: boolean;
      }
    ],
    "view"
  >;

  assignRole: TypedContractMethod<
    [agent: AddressLike, role: BytesLike, capabilities: BytesLike[]],
    [void],
    "nonpayable"
  >;

  canBeAutomated: TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  getAgentConfig: TypedContractMethod<
    [agent: AddressLike],
    [AgentCoordinator.AgentConfigStructOutput],
    "view"
  >;

  getAgentRoles: TypedContractMethod<[agent: AddressLike], [string[]], "view">;

  getCapabilitiesForRole: TypedContractMethod<
    [role: BytesLike],
    [string[]],
    "view"
  >;

  getMaxGasPerCall: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  getRoleMembers: TypedContractMethod<[role: BytesLike], [string[]], "view">;

  grantCapability: TypedContractMethod<
    [agent: AddressLike, capability: BytesLike],
    [void],
    "nonpayable"
  >;

  hasCapability: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [agent: AddressLike, role: BytesLike],
    [boolean],
    "view"
  >;

  isAgentRegistered: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isContractAgent: TypedContractMethod<[agent: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerAgent: TypedContractMethod<
    [
      agent: AddressLike,
      maxGasPerCall: BigNumberish,
      allowedAutomation: boolean
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeCapability: TypedContractMethod<
    [agent: AddressLike, capability: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [agent: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;

  roleAdmin: TypedContractMethod<[], [string], "view">;

  roleCapabilities: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  roleMembers: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  setAllowedAutomation: TypedContractMethod<
    [agent: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setMaxGasPerCall: TypedContractMethod<
    [agent: AddressLike, newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRoleAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CAN_PAY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CAN_REBALANCE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CAN_SUBSCRIBE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CAN_TRADE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CAN_TRANSFER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CAN_YIELD"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentRoles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, boolean] & {
        isContract: boolean;
        maxGasPerCall: bigint;
        allowedAutomation: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [agent: AddressLike, role: BytesLike, capabilities: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canBeAutomated"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAgentConfig"
  ): TypedContractMethod<
    [agent: AddressLike],
    [AgentCoordinator.AgentConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentRoles"
  ): TypedContractMethod<[agent: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCapabilitiesForRole"
  ): TypedContractMethod<[role: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMaxGasPerCall"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleMembers"
  ): TypedContractMethod<[role: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantCapability"
  ): TypedContractMethod<
    [agent: AddressLike, capability: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasCapability"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [agent: AddressLike, role: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAgentRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isContractAgent"
  ): TypedContractMethod<[agent: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      maxGasPerCall: BigNumberish,
      allowedAutomation: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCapability"
  ): TypedContractMethod<
    [agent: AddressLike, capability: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [agent: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "roleAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "roleCapabilities"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "roleMembers"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAllowedAutomation"
  ): TypedContractMethod<
    [agent: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxGasPerCall"
  ): TypedContractMethod<
    [agent: AddressLike, newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRoleAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CapabilityGranted"
  ): TypedContractEvent<
    CapabilityGrantedEvent.InputTuple,
    CapabilityGrantedEvent.OutputTuple,
    CapabilityGrantedEvent.OutputObject
  >;
  getEvent(
    key: "CapabilityRevoked"
  ): TypedContractEvent<
    CapabilityRevokedEvent.InputTuple,
    CapabilityRevokedEvent.OutputTuple,
    CapabilityRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleDefinedForAgent"
  ): TypedContractEvent<
    RoleDefinedForAgentEvent.InputTuple,
    RoleDefinedForAgentEvent.OutputTuple,
    RoleDefinedForAgentEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(address,bool,uint256,bool)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "CapabilityGranted(address,bytes32)": TypedContractEvent<
      CapabilityGrantedEvent.InputTuple,
      CapabilityGrantedEvent.OutputTuple,
      CapabilityGrantedEvent.OutputObject
    >;
    CapabilityGranted: TypedContractEvent<
      CapabilityGrantedEvent.InputTuple,
      CapabilityGrantedEvent.OutputTuple,
      CapabilityGrantedEvent.OutputObject
    >;

    "CapabilityRevoked(address,bytes32)": TypedContractEvent<
      CapabilityRevokedEvent.InputTuple,
      CapabilityRevokedEvent.OutputTuple,
      CapabilityRevokedEvent.OutputObject
    >;
    CapabilityRevoked: TypedContractEvent<
      CapabilityRevokedEvent.InputTuple,
      CapabilityRevokedEvent.OutputTuple,
      CapabilityRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RoleAdminChanged(address,address)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleDefinedForAgent(address,bytes32,bytes32[])": TypedContractEvent<
      RoleDefinedForAgentEvent.InputTuple,
      RoleDefinedForAgentEvent.OutputTuple,
      RoleDefinedForAgentEvent.OutputObject
    >;
    RoleDefinedForAgent: TypedContractEvent<
      RoleDefinedForAgentEvent.InputTuple,
      RoleDefinedForAgentEvent.OutputTuple,
      RoleDefinedForAgentEvent.OutputObject
    >;

    "RoleRevoked(address,bytes32)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
