/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  AuditHookCaller,
  AuditHookCallerInterface,
} from "../../../../contracts/execution/ExecutionController.sol/AuditHookCaller";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "hook",
        type: "address",
      },
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "paymentType",
        type: "string",
      },
    ],
    name: "call",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061031d806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063edafcd5b14610030575b600080fd5b61004361003e366004610166565b610045565b005b6000856001600160a01b0316858585856040516024016100689493929190610277565b60408051601f198184030181529181526020820180516001600160e01b0316635df16beb60e01b1790525161009d91906102cb565b6000604051808303816000865af19150503d80600081146100da576040519150601f19603f3d011682016040523d82523d6000602084013e6100df565b606091505b505090508061012c5760405162461bcd60e51b81526020600482015260156024820152741150ce88185d591a5d081a1bdbdac819985a5b1959605a1b604482015260640160405180910390fd5b505050505050565b80356001600160a01b038116811461014b57600080fd5b919050565b634e487b7160e01b600052604160045260246000fd5b600080600080600060a0868803121561017e57600080fd5b61018786610134565b945061019560208701610134565b93506101a360408701610134565b925060608601359150608086013567ffffffffffffffff808211156101c757600080fd5b818801915088601f8301126101db57600080fd5b8135818111156101ed576101ed610150565b604051601f8201601f19908116603f0116810190838211818310171561021557610215610150565b816040528281528b602084870101111561022e57600080fd5b8260208601602083013760006020848301015280955050505050509295509295909350565b60005b8381101561026e578181015183820152602001610256565b50506000910152565b600060018060a01b0380871683528086166020840152508360408301526080606083015282518060808401526102b48160a0850160208701610253565b601f01601f19169190910160a00195945050505050565b600082516102dd818460208701610253565b919091019291505056fea2646970667358221220f21e384080d00dd4931378f55a451303d06fb46d628fe6c1cc5d5635d71b57ec64736f6c63430008140033";

type AuditHookCallerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuditHookCallerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuditHookCaller__factory extends ContractFactory {
  constructor(...args: AuditHookCallerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuditHookCaller & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AuditHookCaller__factory {
    return super.connect(runner) as AuditHookCaller__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuditHookCallerInterface {
    return new Interface(_abi) as AuditHookCallerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuditHookCaller {
    return new Contract(address, _abi, runner) as unknown as AuditHookCaller;
  }
}
