/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentSafe,
  IAgentSafeInterface,
} from "../../../../contracts/execution/ExecutionController.sol/IAgentSafe";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "agentExecute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "agentExecuteFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "allowNonLSP1Recipient",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "tokenData",
        type: "bytes",
      },
    ],
    name: "agentTransferToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "allowNonLSP1Recipient",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "tokenData",
        type: "bytes",
      },
    ],
    name: "agentTransferTokenFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentSafe__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentSafeInterface {
    return new Interface(_abi) as IAgentSafeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAgentSafe {
    return new Contract(address, _abi, runner) as unknown as IAgentSafe;
  }
}
