/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILSP7,
  ILSP7Interface,
} from "../../../../contracts/execution/ExecutionController.sol/ILSP7";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILSP7__factory {
  static readonly abi = _abi;
  static createInterface(): ILSP7Interface {
    return new Interface(_abi) as ILSP7Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILSP7 {
    return new Contract(address, _abi, runner) as unknown as ILSP7;
  }
}
