/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AgentBudgetPolicyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_AGENTS"
      | "agentBudget"
      | "agentCount"
      | "agentLastPeriodStart"
      | "agentSpent"
      | "budgetToken"
      | "getAgentRemaining"
      | "getPeriodDuration"
      | "getTimeUntilReset"
      | "owner"
      | "period"
      | "periodStart"
      | "policyEngine"
      | "renounceOwnership"
      | "setAgentBudget"
      | "setAgentBudgetsBatch"
      | "syncPeriodStart"
      | "transferOwnership"
      | "validate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentBudgetSet"
      | "AgentBudgetSpent"
      | "OwnershipTransferred"
      | "PeriodReset"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_AGENTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentBudget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentLastPeriodStart",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentSpent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "budgetToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentRemaining",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPeriodDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeUntilReset",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "period", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "periodStart",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentBudget",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentBudgetsBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "syncPeriodStart",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validate",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_AGENTS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentLastPeriodStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentSpent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "budgetToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPeriodDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeUntilReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "period", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "periodStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentBudgetsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "syncPeriodStart",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "validate", data: BytesLike): Result;
}

export namespace AgentBudgetSetEvent {
  export type InputTuple = [agent: AddressLike, newBudget: BigNumberish];
  export type OutputTuple = [agent: string, newBudget: bigint];
  export interface OutputObject {
    agent: string;
    newBudget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentBudgetSpentEvent {
  export type InputTuple = [
    agent: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    newSpent: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    token: string,
    amount: bigint,
    newSpent: bigint
  ];
  export interface OutputObject {
    agent: string;
    token: string;
    amount: bigint;
    newSpent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeriodResetEvent {
  export type InputTuple = [newPeriodStart: BigNumberish];
  export type OutputTuple = [newPeriodStart: bigint];
  export interface OutputObject {
    newPeriodStart: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentBudgetPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): AgentBudgetPolicy;
  waitForDeployment(): Promise<this>;

  interface: AgentBudgetPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_AGENTS: TypedContractMethod<[], [bigint], "view">;

  agentBudget: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agentLastPeriodStart: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  agentSpent: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  budgetToken: TypedContractMethod<[], [string], "view">;

  getAgentRemaining: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getPeriodDuration: TypedContractMethod<[], [bigint], "view">;

  getTimeUntilReset: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  period: TypedContractMethod<[], [bigint], "view">;

  periodStart: TypedContractMethod<[], [bigint], "view">;

  policyEngine: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAgentBudget: TypedContractMethod<
    [agent: AddressLike, budget: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAgentBudgetsBatch: TypedContractMethod<
    [agents: AddressLike[], budgets: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  syncPeriodStart: TypedContractMethod<
    [newPeriodStart: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  validate: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      arg2: AddressLike,
      amount: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_AGENTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentBudget"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentLastPeriodStart"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentSpent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "budgetToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentRemaining"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPeriodDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimeUntilReset"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "period"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "periodStart"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentBudget"
  ): TypedContractMethod<
    [agent: AddressLike, budget: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentBudgetsBatch"
  ): TypedContractMethod<
    [agents: AddressLike[], budgets: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "syncPeriodStart"
  ): TypedContractMethod<[newPeriodStart: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "validate"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      arg2: AddressLike,
      amount: BigNumberish,
      arg4: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentBudgetSet"
  ): TypedContractEvent<
    AgentBudgetSetEvent.InputTuple,
    AgentBudgetSetEvent.OutputTuple,
    AgentBudgetSetEvent.OutputObject
  >;
  getEvent(
    key: "AgentBudgetSpent"
  ): TypedContractEvent<
    AgentBudgetSpentEvent.InputTuple,
    AgentBudgetSpentEvent.OutputTuple,
    AgentBudgetSpentEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PeriodReset"
  ): TypedContractEvent<
    PeriodResetEvent.InputTuple,
    PeriodResetEvent.OutputTuple,
    PeriodResetEvent.OutputObject
  >;

  filters: {
    "AgentBudgetSet(address,uint256)": TypedContractEvent<
      AgentBudgetSetEvent.InputTuple,
      AgentBudgetSetEvent.OutputTuple,
      AgentBudgetSetEvent.OutputObject
    >;
    AgentBudgetSet: TypedContractEvent<
      AgentBudgetSetEvent.InputTuple,
      AgentBudgetSetEvent.OutputTuple,
      AgentBudgetSetEvent.OutputObject
    >;

    "AgentBudgetSpent(address,address,uint256,uint256)": TypedContractEvent<
      AgentBudgetSpentEvent.InputTuple,
      AgentBudgetSpentEvent.OutputTuple,
      AgentBudgetSpentEvent.OutputObject
    >;
    AgentBudgetSpent: TypedContractEvent<
      AgentBudgetSpentEvent.InputTuple,
      AgentBudgetSpentEvent.OutputTuple,
      AgentBudgetSpentEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PeriodReset(uint256)": TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;
    PeriodReset: TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;
  };
}
