/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILSP9Vault,
  ILSP9VaultInterface,
} from "../../../../@lukso/lsp9-contracts/contracts/ILSP9Vault";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "data",
        type: "bytes[]",
      },
    ],
    name: "batchCalls",
    outputs: [
      {
        internalType: "bytes[]",
        name: "results",
        type: "bytes[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILSP9Vault__factory {
  static readonly abi = _abi;
  static createInterface(): ILSP9VaultInterface {
    return new Interface(_abi) as ILSP9VaultInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ILSP9Vault {
    return new Contract(address, _abi, runner) as unknown as ILSP9Vault;
  }
}
