/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILSP20CallVerifier,
  ILSP20CallVerifierInterface,
} from "../../../../@lukso/lsp20-contracts/contracts/ILSP20CallVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "requestor",
        type: "address",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "callData",
        type: "bytes",
      },
    ],
    name: "lsp20VerifyCall",
    outputs: [
      {
        internalType: "bytes4",
        name: "returnedStatus",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "callHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "callResult",
        type: "bytes",
      },
    ],
    name: "lsp20VerifyCallResult",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILSP20CallVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ILSP20CallVerifierInterface {
    return new Interface(_abi) as ILSP20CallVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILSP20CallVerifier {
    return new Contract(address, _abi, runner) as unknown as ILSP20CallVerifier;
  }
}
