/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyEngineSimulationABP,
  IPolicyEngineSimulationABPInterface,
} from "../../../../contracts/policies/AgentBudgetPolicy.sol/IPolicyEngineSimulationABP";

const _abi = [
  {
    inputs: [],
    name: "simulationActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPolicyEngineSimulationABP__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyEngineSimulationABPInterface {
    return new Interface(_abi) as IPolicyEngineSimulationABPInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyEngineSimulationABP {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPolicyEngineSimulationABP;
  }
}
