/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TemplateFactory {
  export type TemplateParamsStruct = {
    templateId: BytesLike;
    customBudget: BigNumberish;
    customExpiration: BigNumberish;
    customMerchants: AddressLike[];
    customLabel: string;
  };

  export type TemplateParamsStructOutput = [
    templateId: string,
    customBudget: bigint,
    customExpiration: bigint,
    customMerchants: string[],
    customLabel: string
  ] & {
    templateId: string;
    customBudget: bigint;
    customExpiration: bigint;
    customMerchants: string[];
    customLabel: string;
  };
}

export declare namespace AgentVaultRegistry {
  export type VaultRecordStruct = {
    safe: AddressLike;
    keyManager: AddressLike;
    policyEngine: AddressLike;
    label: string;
  };

  export type VaultRecordStructOutput = [
    safe: string,
    keyManager: string,
    policyEngine: string,
    label: string
  ] & { safe: string; keyManager: string; policyEngine: string; label: string };
}

export interface TemplateFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createFromTemplate" | "getTemplateName" | "registry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TemplateApplied"): EventFragment;

  encodeFunctionData(
    functionFragment: "createFromTemplate",
    values: [
      TemplateFactory.TemplateParamsStruct,
      AddressLike[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTemplateName",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createFromTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTemplateName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
}

export namespace TemplateAppliedEvent {
  export type InputTuple = [
    templateId: BytesLike,
    owner: AddressLike,
    safe: AddressLike,
    label: string
  ];
  export type OutputTuple = [
    templateId: string,
    owner: string,
    safe: string,
    label: string
  ];
  export interface OutputObject {
    templateId: string;
    owner: string;
    safe: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TemplateFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TemplateFactory;
  waitForDeployment(): Promise<this>;

  interface: TemplateFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createFromTemplate: TypedContractMethod<
    [
      tp: TemplateFactory.TemplateParamsStruct,
      agents: AddressLike[],
      agentBudgets: BigNumberish[]
    ],
    [AgentVaultRegistry.VaultRecordStructOutput],
    "nonpayable"
  >;

  getTemplateName: TypedContractMethod<
    [templateId: BytesLike],
    [string],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createFromTemplate"
  ): TypedContractMethod<
    [
      tp: TemplateFactory.TemplateParamsStruct,
      agents: AddressLike[],
      agentBudgets: BigNumberish[]
    ],
    [AgentVaultRegistry.VaultRecordStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTemplateName"
  ): TypedContractMethod<[templateId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "TemplateApplied"
  ): TypedContractEvent<
    TemplateAppliedEvent.InputTuple,
    TemplateAppliedEvent.OutputTuple,
    TemplateAppliedEvent.OutputObject
  >;

  filters: {
    "TemplateApplied(bytes32,address,address,string)": TypedContractEvent<
      TemplateAppliedEvent.InputTuple,
      TemplateAppliedEvent.OutputTuple,
      TemplateAppliedEvent.OutputObject
    >;
    TemplateApplied: TypedContractEvent<
      TemplateAppliedEvent.InputTuple,
      TemplateAppliedEvent.OutputTuple,
      TemplateAppliedEvent.OutputObject
    >;
  };
}
