/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILSP25ExecuteRelayCall,
  ILSP25ExecuteRelayCallInterface,
} from "../../../../@lukso/lsp25-contracts/contracts/ILSP25ExecuteRelayCall";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "validityTimestamps",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
    ],
    name: "executeRelayCall",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "signatures",
        type: "bytes[]",
      },
      {
        internalType: "uint256[]",
        name: "nonces",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "validityTimestamps",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
      {
        internalType: "bytes[]",
        name: "payloads",
        type: "bytes[]",
      },
    ],
    name: "executeRelayCallBatch",
    outputs: [
      {
        internalType: "bytes[]",
        name: "",
        type: "bytes[]",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "channelId",
        type: "uint128",
      },
    ],
    name: "getNonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILSP25ExecuteRelayCall__factory {
  static readonly abi = _abi;
  static createInterface(): ILSP25ExecuteRelayCallInterface {
    return new Interface(_abi) as ILSP25ExecuteRelayCallInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILSP25ExecuteRelayCall {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILSP25ExecuteRelayCall;
  }
}
