/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "OwnableUnset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUnset__factory>;
    getContractFactory(
      name: "ERC725XCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC725XCore__factory>;
    getContractFactory(
      name: "ERC725Y",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC725Y__factory>;
    getContractFactory(
      name: "ERC725YCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC725YCore__factory>;
    getContractFactory(
      name: "IERC725X",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC725X__factory>;
    getContractFactory(
      name: "IERC725Y",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC725Y__factory>;
    getContractFactory(
      name: "ILSP1UniversalReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP1UniversalReceiver__factory>;
    getContractFactory(
      name: "ILSP1UniversalReceiverDelegate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP1UniversalReceiverDelegate__factory>;
    getContractFactory(
      name: "ILSP14Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP14Ownable2Step__factory>;
    getContractFactory(
      name: "LSP14Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP14Ownable2Step__factory>;
    getContractFactory(
      name: "LSP17Extendable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP17Extendable__factory>;
    getContractFactory(
      name: "ILSP20CallVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP20CallVerifier__factory>;
    getContractFactory(
      name: "ILSP25ExecuteRelayCall",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP25ExecuteRelayCall__factory>;
    getContractFactory(
      name: "ILSP6KeyManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP6KeyManager__factory>;
    getContractFactory(
      name: "LSP6KeyManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP6KeyManager__factory>;
    getContractFactory(
      name: "LSP6KeyManagerCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP6KeyManagerCore__factory>;
    getContractFactory(
      name: "Version",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Version__factory>;
    getContractFactory(
      name: "ILSP9Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP9Vault__factory>;
    getContractFactory(
      name: "LSP9Vault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP9Vault__factory>;
    getContractFactory(
      name: "LSP9VaultCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP9VaultCore__factory>;
    getContractFactory(
      name: "Version",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Version__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1271__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AgentSafe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentSafe__factory>;
    getContractFactory(
      name: "ILSP7",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP7__factory>;
    getContractFactory(
      name: "IPolicyEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPolicyEngine__factory>;
    getContractFactory(
      name: "AgentVaultRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentVaultRegistry__factory>;
    getContractFactory(
      name: "TaskScheduler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TaskScheduler__factory>;
    getContractFactory(
      name: "AgentCoordinator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentCoordinator__factory>;
    getContractFactory(
      name: "AuditHookCaller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AuditHookCaller__factory>;
    getContractFactory(
      name: "ExecutionController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExecutionController__factory>;
    getContractFactory(
      name: "IAgentSafe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentSafe__factory>;
    getContractFactory(
      name: "ILSP7",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP7__factory>;
    getContractFactory(
      name: "IPolicyEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPolicyEngine__factory>;
    getContractFactory(
      name: "RateLimiter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RateLimiter__factory>;
    getContractFactory(
      name: "SharedBudgetPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SharedBudgetPool__factory>;
    getContractFactory(
      name: "VaultDirectory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultDirectory__factory>;
    getContractFactory(
      name: "MerchantRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerchantRegistry__factory>;
    getContractFactory(
      name: "IAgentSafeReentrant",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgentSafeReentrant__factory>;
    getContractFactory(
      name: "MockReentrantToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockReentrantToken__factory>;
    getContractFactory(
      name: "AgentBudgetPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentBudgetPolicy__factory>;
    getContractFactory(
      name: "IPolicyEngineSimulationABP",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPolicyEngineSimulationABP__factory>;
    getContractFactory(
      name: "BudgetPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BudgetPolicy__factory>;
    getContractFactory(
      name: "IPolicyEngineSimulation",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPolicyEngineSimulation__factory>;
    getContractFactory(
      name: "ExpirationPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExpirationPolicy__factory>;
    getContractFactory(
      name: "IPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPolicy__factory>;
    getContractFactory(
      name: "MerchantPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerchantPolicy__factory>;
    getContractFactory(
      name: "ISharedBudgetPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISharedBudgetPool__factory>;
    getContractFactory(
      name: "SharedBudgetPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SharedBudgetPolicy__factory>;
    getContractFactory(
      name: "PolicyEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolicyEngine__factory>;
    getContractFactory(
      name: "TemplateFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TemplateFactory__factory>;

    getContractAt(
      name: "OwnableUnset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUnset>;
    getContractAt(
      name: "ERC725XCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC725XCore>;
    getContractAt(
      name: "ERC725Y",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC725Y>;
    getContractAt(
      name: "ERC725YCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC725YCore>;
    getContractAt(
      name: "IERC725X",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC725X>;
    getContractAt(
      name: "IERC725Y",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC725Y>;
    getContractAt(
      name: "ILSP1UniversalReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP1UniversalReceiver>;
    getContractAt(
      name: "ILSP1UniversalReceiverDelegate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP1UniversalReceiverDelegate>;
    getContractAt(
      name: "ILSP14Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP14Ownable2Step>;
    getContractAt(
      name: "LSP14Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP14Ownable2Step>;
    getContractAt(
      name: "LSP17Extendable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP17Extendable>;
    getContractAt(
      name: "ILSP20CallVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP20CallVerifier>;
    getContractAt(
      name: "ILSP25ExecuteRelayCall",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP25ExecuteRelayCall>;
    getContractAt(
      name: "ILSP6KeyManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP6KeyManager>;
    getContractAt(
      name: "LSP6KeyManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP6KeyManager>;
    getContractAt(
      name: "LSP6KeyManagerCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP6KeyManagerCore>;
    getContractAt(
      name: "Version",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Version>;
    getContractAt(
      name: "ILSP9Vault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP9Vault>;
    getContractAt(
      name: "LSP9Vault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP9Vault>;
    getContractAt(
      name: "LSP9VaultCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP9VaultCore>;
    getContractAt(
      name: "Version",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Version>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1271",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1271>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AgentSafe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentSafe>;
    getContractAt(
      name: "ILSP7",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP7>;
    getContractAt(
      name: "IPolicyEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPolicyEngine>;
    getContractAt(
      name: "AgentVaultRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentVaultRegistry>;
    getContractAt(
      name: "TaskScheduler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TaskScheduler>;
    getContractAt(
      name: "AgentCoordinator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentCoordinator>;
    getContractAt(
      name: "AuditHookCaller",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AuditHookCaller>;
    getContractAt(
      name: "ExecutionController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExecutionController>;
    getContractAt(
      name: "IAgentSafe",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentSafe>;
    getContractAt(
      name: "ILSP7",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP7>;
    getContractAt(
      name: "IPolicyEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPolicyEngine>;
    getContractAt(
      name: "RateLimiter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RateLimiter>;
    getContractAt(
      name: "SharedBudgetPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SharedBudgetPool>;
    getContractAt(
      name: "VaultDirectory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultDirectory>;
    getContractAt(
      name: "MerchantRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerchantRegistry>;
    getContractAt(
      name: "IAgentSafeReentrant",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgentSafeReentrant>;
    getContractAt(
      name: "MockReentrantToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockReentrantToken>;
    getContractAt(
      name: "AgentBudgetPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentBudgetPolicy>;
    getContractAt(
      name: "IPolicyEngineSimulationABP",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPolicyEngineSimulationABP>;
    getContractAt(
      name: "BudgetPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BudgetPolicy>;
    getContractAt(
      name: "IPolicyEngineSimulation",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPolicyEngineSimulation>;
    getContractAt(
      name: "ExpirationPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ExpirationPolicy>;
    getContractAt(
      name: "IPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPolicy>;
    getContractAt(
      name: "MerchantPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerchantPolicy>;
    getContractAt(
      name: "ISharedBudgetPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISharedBudgetPool>;
    getContractAt(
      name: "SharedBudgetPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SharedBudgetPolicy>;
    getContractAt(
      name: "PolicyEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolicyEngine>;
    getContractAt(
      name: "TemplateFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TemplateFactory>;

    deployContract(
      name: "OwnableUnset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUnset>;
    deployContract(
      name: "ERC725XCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725XCore>;
    deployContract(
      name: "ERC725Y",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725Y>;
    deployContract(
      name: "ERC725YCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725YCore>;
    deployContract(
      name: "IERC725X",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC725X>;
    deployContract(
      name: "IERC725Y",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC725Y>;
    deployContract(
      name: "ILSP1UniversalReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP1UniversalReceiver>;
    deployContract(
      name: "ILSP1UniversalReceiverDelegate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP1UniversalReceiverDelegate>;
    deployContract(
      name: "ILSP14Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP14Ownable2Step>;
    deployContract(
      name: "LSP14Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP14Ownable2Step>;
    deployContract(
      name: "LSP17Extendable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP17Extendable>;
    deployContract(
      name: "ILSP20CallVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP20CallVerifier>;
    deployContract(
      name: "ILSP25ExecuteRelayCall",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP25ExecuteRelayCall>;
    deployContract(
      name: "ILSP6KeyManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP6KeyManager>;
    deployContract(
      name: "LSP6KeyManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP6KeyManager>;
    deployContract(
      name: "LSP6KeyManagerCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP6KeyManagerCore>;
    deployContract(
      name: "Version",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Version>;
    deployContract(
      name: "ILSP9Vault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP9Vault>;
    deployContract(
      name: "LSP9Vault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP9Vault>;
    deployContract(
      name: "LSP9VaultCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP9VaultCore>;
    deployContract(
      name: "Version",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Version>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1271",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1271>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AgentSafe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentSafe>;
    deployContract(
      name: "ILSP7",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP7>;
    deployContract(
      name: "IPolicyEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngine>;
    deployContract(
      name: "AgentVaultRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentVaultRegistry>;
    deployContract(
      name: "TaskScheduler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TaskScheduler>;
    deployContract(
      name: "AgentCoordinator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentCoordinator>;
    deployContract(
      name: "AuditHookCaller",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AuditHookCaller>;
    deployContract(
      name: "ExecutionController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExecutionController>;
    deployContract(
      name: "IAgentSafe",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentSafe>;
    deployContract(
      name: "ILSP7",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP7>;
    deployContract(
      name: "IPolicyEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngine>;
    deployContract(
      name: "RateLimiter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RateLimiter>;
    deployContract(
      name: "SharedBudgetPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SharedBudgetPool>;
    deployContract(
      name: "VaultDirectory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultDirectory>;
    deployContract(
      name: "MerchantRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerchantRegistry>;
    deployContract(
      name: "IAgentSafeReentrant",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentSafeReentrant>;
    deployContract(
      name: "MockReentrantToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockReentrantToken>;
    deployContract(
      name: "AgentBudgetPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentBudgetPolicy>;
    deployContract(
      name: "IPolicyEngineSimulationABP",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngineSimulationABP>;
    deployContract(
      name: "BudgetPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BudgetPolicy>;
    deployContract(
      name: "IPolicyEngineSimulation",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngineSimulation>;
    deployContract(
      name: "ExpirationPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExpirationPolicy>;
    deployContract(
      name: "IPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicy>;
    deployContract(
      name: "MerchantPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerchantPolicy>;
    deployContract(
      name: "ISharedBudgetPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISharedBudgetPool>;
    deployContract(
      name: "SharedBudgetPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SharedBudgetPolicy>;
    deployContract(
      name: "PolicyEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolicyEngine>;
    deployContract(
      name: "TemplateFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TemplateFactory>;

    deployContract(
      name: "OwnableUnset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUnset>;
    deployContract(
      name: "ERC725XCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725XCore>;
    deployContract(
      name: "ERC725Y",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725Y>;
    deployContract(
      name: "ERC725YCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725YCore>;
    deployContract(
      name: "IERC725X",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC725X>;
    deployContract(
      name: "IERC725Y",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC725Y>;
    deployContract(
      name: "ILSP1UniversalReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP1UniversalReceiver>;
    deployContract(
      name: "ILSP1UniversalReceiverDelegate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP1UniversalReceiverDelegate>;
    deployContract(
      name: "ILSP14Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP14Ownable2Step>;
    deployContract(
      name: "LSP14Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP14Ownable2Step>;
    deployContract(
      name: "LSP17Extendable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP17Extendable>;
    deployContract(
      name: "ILSP20CallVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP20CallVerifier>;
    deployContract(
      name: "ILSP25ExecuteRelayCall",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP25ExecuteRelayCall>;
    deployContract(
      name: "ILSP6KeyManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP6KeyManager>;
    deployContract(
      name: "LSP6KeyManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP6KeyManager>;
    deployContract(
      name: "LSP6KeyManagerCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP6KeyManagerCore>;
    deployContract(
      name: "Version",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Version>;
    deployContract(
      name: "ILSP9Vault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP9Vault>;
    deployContract(
      name: "LSP9Vault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP9Vault>;
    deployContract(
      name: "LSP9VaultCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP9VaultCore>;
    deployContract(
      name: "Version",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Version>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1271",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1271>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AgentSafe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentSafe>;
    deployContract(
      name: "ILSP7",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP7>;
    deployContract(
      name: "IPolicyEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngine>;
    deployContract(
      name: "AgentVaultRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentVaultRegistry>;
    deployContract(
      name: "TaskScheduler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TaskScheduler>;
    deployContract(
      name: "AgentCoordinator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentCoordinator>;
    deployContract(
      name: "AuditHookCaller",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AuditHookCaller>;
    deployContract(
      name: "ExecutionController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExecutionController>;
    deployContract(
      name: "IAgentSafe",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentSafe>;
    deployContract(
      name: "ILSP7",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP7>;
    deployContract(
      name: "IPolicyEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngine>;
    deployContract(
      name: "RateLimiter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RateLimiter>;
    deployContract(
      name: "SharedBudgetPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SharedBudgetPool>;
    deployContract(
      name: "VaultDirectory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VaultDirectory>;
    deployContract(
      name: "MerchantRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerchantRegistry>;
    deployContract(
      name: "IAgentSafeReentrant",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgentSafeReentrant>;
    deployContract(
      name: "MockReentrantToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockReentrantToken>;
    deployContract(
      name: "AgentBudgetPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentBudgetPolicy>;
    deployContract(
      name: "IPolicyEngineSimulationABP",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngineSimulationABP>;
    deployContract(
      name: "BudgetPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BudgetPolicy>;
    deployContract(
      name: "IPolicyEngineSimulation",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyEngineSimulation>;
    deployContract(
      name: "ExpirationPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ExpirationPolicy>;
    deployContract(
      name: "IPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicy>;
    deployContract(
      name: "MerchantPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerchantPolicy>;
    deployContract(
      name: "ISharedBudgetPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISharedBudgetPool>;
    deployContract(
      name: "SharedBudgetPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SharedBudgetPolicy>;
    deployContract(
      name: "PolicyEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolicyEngine>;
    deployContract(
      name: "TemplateFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TemplateFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
