/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AgentSafeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY"
      | "RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD"
      | "VERSION"
      | "acceptOwnership"
      | "agentExecute"
      | "agentExecuteFor"
      | "agentTransferToken"
      | "agentTransferTokenFor"
      | "batchCalls"
      | "execute"
      | "executeBatch"
      | "executionController"
      | "getData"
      | "getDataBatch"
      | "owner"
      | "pendingOwner"
      | "policyEngine"
      | "renounceOwnership"
      | "setData"
      | "setDataBatch"
      | "setExecutionController"
      | "setKeyManager"
      | "setPolicyEngine"
      | "supportsInterface"
      | "transferOwnership"
      | "universalReceiver"
      | "vaultKeyManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentPaymentExecuted"
      | "AgentTokenPaymentExecuted"
      | "ContractCreated"
      | "DataChanged"
      | "Executed"
      | "OwnershipRenounced"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PolicyEngineSet"
      | "RenounceOwnershipStarted"
      | "UniversalReceiver"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentExecute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentExecuteFor",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentTransferToken",
    values: [AddressLike, AddressLike, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "agentTransferTokenFor",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      boolean,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCalls",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [BigNumberish[], AddressLike[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executionController",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getData", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getDataBatch",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setData",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDataBatch",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutionController",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeyManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicyEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "universalReceiver",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultKeyManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentExecuteFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentTransferToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentTransferTokenFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchCalls", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDataBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDataBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutionController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKeyManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "universalReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultKeyManager",
    data: BytesLike
  ): Result;
}

export namespace AgentPaymentExecutedEvent {
  export type InputTuple = [
    keyManager: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [keyManager: string, to: string, amount: bigint];
  export interface OutputObject {
    keyManager: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentTokenPaymentExecutedEvent {
  export type InputTuple = [
    keyManager: AddressLike,
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    keyManager: string,
    token: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    keyManager: string;
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractCreatedEvent {
  export type InputTuple = [
    operationType: BigNumberish,
    contractAddress: AddressLike,
    value: BigNumberish,
    salt: BytesLike
  ];
  export type OutputTuple = [
    operationType: bigint,
    contractAddress: string,
    value: bigint,
    salt: string
  ];
  export interface OutputObject {
    operationType: bigint;
    contractAddress: string;
    value: bigint;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataChangedEvent {
  export type InputTuple = [dataKey: BytesLike, dataValue: BytesLike];
  export type OutputTuple = [dataKey: string, dataValue: string];
  export interface OutputObject {
    dataKey: string;
    dataValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    operationType: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    selector: BytesLike
  ];
  export type OutputTuple = [
    operationType: bigint,
    target: string,
    value: bigint,
    selector: string
  ];
  export interface OutputObject {
    operationType: bigint;
    target: string;
    value: bigint;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipRenouncedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyEngineSetEvent {
  export type InputTuple = [pe: AddressLike];
  export type OutputTuple = [pe: string];
  export interface OutputObject {
    pe: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RenounceOwnershipStartedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UniversalReceiverEvent {
  export type InputTuple = [
    from: AddressLike,
    value: BigNumberish,
    typeId: BytesLike,
    receivedData: BytesLike,
    returnedValue: BytesLike
  ];
  export type OutputTuple = [
    from: string,
    value: bigint,
    typeId: string,
    receivedData: string,
    returnedValue: string
  ];
  export interface OutputObject {
    from: string;
    value: bigint;
    typeId: string;
    receivedData: string;
    returnedValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentSafe extends BaseContract {
  connect(runner?: ContractRunner | null): AgentSafe;
  waitForDeployment(): Promise<this>;

  interface: AgentSafeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  agentExecute: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  agentExecuteFor: TypedContractMethod<
    [
      agent: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  agentTransferToken: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  agentTransferTokenFor: TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  batchCalls: TypedContractMethod<
    [data: BytesLike[]],
    [string[]],
    "nonpayable"
  >;

  execute: TypedContractMethod<
    [
      operationType: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [string],
    "payable"
  >;

  executeBatch: TypedContractMethod<
    [
      operationsType: BigNumberish[],
      targets: AddressLike[],
      values: BigNumberish[],
      datas: BytesLike[]
    ],
    [string[]],
    "payable"
  >;

  executionController: TypedContractMethod<[], [string], "view">;

  getData: TypedContractMethod<[dataKey: BytesLike], [string], "view">;

  getDataBatch: TypedContractMethod<
    [dataKeys: BytesLike[]],
    [string[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  policyEngine: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setData: TypedContractMethod<
    [dataKey: BytesLike, dataValue: BytesLike],
    [void],
    "payable"
  >;

  setDataBatch: TypedContractMethod<
    [dataKeys: BytesLike[], dataValues: BytesLike[]],
    [void],
    "payable"
  >;

  setExecutionController: TypedContractMethod<
    [ec: AddressLike],
    [void],
    "nonpayable"
  >;

  setKeyManager: TypedContractMethod<[km: AddressLike], [void], "nonpayable">;

  setPolicyEngine: TypedContractMethod<[pe: AddressLike], [void], "nonpayable">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  universalReceiver: TypedContractMethod<
    [typeId: BytesLike, receivedData: BytesLike],
    [string],
    "payable"
  >;

  vaultKeyManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "RENOUNCE_OWNERSHIP_CONFIRMATION_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RENOUNCE_OWNERSHIP_CONFIRMATION_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentExecute"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentExecuteFor"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentTransferToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentTransferTokenFor"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      allowNonLSP1Recipient: boolean,
      tokenData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchCalls"
  ): TypedContractMethod<[data: BytesLike[]], [string[]], "nonpayable">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      operationType: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [
      operationsType: BigNumberish[],
      targets: AddressLike[],
      values: BigNumberish[],
      datas: BytesLike[]
    ],
    [string[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executionController"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getData"
  ): TypedContractMethod<[dataKey: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDataBatch"
  ): TypedContractMethod<[dataKeys: BytesLike[]], [string[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setData"
  ): TypedContractMethod<
    [dataKey: BytesLike, dataValue: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setDataBatch"
  ): TypedContractMethod<
    [dataKeys: BytesLike[], dataValues: BytesLike[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setExecutionController"
  ): TypedContractMethod<[ec: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKeyManager"
  ): TypedContractMethod<[km: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicyEngine"
  ): TypedContractMethod<[pe: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "universalReceiver"
  ): TypedContractMethod<
    [typeId: BytesLike, receivedData: BytesLike],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "vaultKeyManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentPaymentExecuted"
  ): TypedContractEvent<
    AgentPaymentExecutedEvent.InputTuple,
    AgentPaymentExecutedEvent.OutputTuple,
    AgentPaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "AgentTokenPaymentExecuted"
  ): TypedContractEvent<
    AgentTokenPaymentExecutedEvent.InputTuple,
    AgentTokenPaymentExecutedEvent.OutputTuple,
    AgentTokenPaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ContractCreated"
  ): TypedContractEvent<
    ContractCreatedEvent.InputTuple,
    ContractCreatedEvent.OutputTuple,
    ContractCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DataChanged"
  ): TypedContractEvent<
    DataChangedEvent.InputTuple,
    DataChangedEvent.OutputTuple,
    DataChangedEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipRenounced"
  ): TypedContractEvent<
    OwnershipRenouncedEvent.InputTuple,
    OwnershipRenouncedEvent.OutputTuple,
    OwnershipRenouncedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyEngineSet"
  ): TypedContractEvent<
    PolicyEngineSetEvent.InputTuple,
    PolicyEngineSetEvent.OutputTuple,
    PolicyEngineSetEvent.OutputObject
  >;
  getEvent(
    key: "RenounceOwnershipStarted"
  ): TypedContractEvent<
    RenounceOwnershipStartedEvent.InputTuple,
    RenounceOwnershipStartedEvent.OutputTuple,
    RenounceOwnershipStartedEvent.OutputObject
  >;
  getEvent(
    key: "UniversalReceiver"
  ): TypedContractEvent<
    UniversalReceiverEvent.InputTuple,
    UniversalReceiverEvent.OutputTuple,
    UniversalReceiverEvent.OutputObject
  >;

  filters: {
    "AgentPaymentExecuted(address,address,uint256)": TypedContractEvent<
      AgentPaymentExecutedEvent.InputTuple,
      AgentPaymentExecutedEvent.OutputTuple,
      AgentPaymentExecutedEvent.OutputObject
    >;
    AgentPaymentExecuted: TypedContractEvent<
      AgentPaymentExecutedEvent.InputTuple,
      AgentPaymentExecutedEvent.OutputTuple,
      AgentPaymentExecutedEvent.OutputObject
    >;

    "AgentTokenPaymentExecuted(address,address,address,uint256)": TypedContractEvent<
      AgentTokenPaymentExecutedEvent.InputTuple,
      AgentTokenPaymentExecutedEvent.OutputTuple,
      AgentTokenPaymentExecutedEvent.OutputObject
    >;
    AgentTokenPaymentExecuted: TypedContractEvent<
      AgentTokenPaymentExecutedEvent.InputTuple,
      AgentTokenPaymentExecutedEvent.OutputTuple,
      AgentTokenPaymentExecutedEvent.OutputObject
    >;

    "ContractCreated(uint256,address,uint256,bytes32)": TypedContractEvent<
      ContractCreatedEvent.InputTuple,
      ContractCreatedEvent.OutputTuple,
      ContractCreatedEvent.OutputObject
    >;
    ContractCreated: TypedContractEvent<
      ContractCreatedEvent.InputTuple,
      ContractCreatedEvent.OutputTuple,
      ContractCreatedEvent.OutputObject
    >;

    "DataChanged(bytes32,bytes)": TypedContractEvent<
      DataChangedEvent.InputTuple,
      DataChangedEvent.OutputTuple,
      DataChangedEvent.OutputObject
    >;
    DataChanged: TypedContractEvent<
      DataChangedEvent.InputTuple,
      DataChangedEvent.OutputTuple,
      DataChangedEvent.OutputObject
    >;

    "Executed(uint256,address,uint256,bytes4)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "OwnershipRenounced()": TypedContractEvent<
      OwnershipRenouncedEvent.InputTuple,
      OwnershipRenouncedEvent.OutputTuple,
      OwnershipRenouncedEvent.OutputObject
    >;
    OwnershipRenounced: TypedContractEvent<
      OwnershipRenouncedEvent.InputTuple,
      OwnershipRenouncedEvent.OutputTuple,
      OwnershipRenouncedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyEngineSet(address)": TypedContractEvent<
      PolicyEngineSetEvent.InputTuple,
      PolicyEngineSetEvent.OutputTuple,
      PolicyEngineSetEvent.OutputObject
    >;
    PolicyEngineSet: TypedContractEvent<
      PolicyEngineSetEvent.InputTuple,
      PolicyEngineSetEvent.OutputTuple,
      PolicyEngineSetEvent.OutputObject
    >;

    "RenounceOwnershipStarted()": TypedContractEvent<
      RenounceOwnershipStartedEvent.InputTuple,
      RenounceOwnershipStartedEvent.OutputTuple,
      RenounceOwnershipStartedEvent.OutputObject
    >;
    RenounceOwnershipStarted: TypedContractEvent<
      RenounceOwnershipStartedEvent.InputTuple,
      RenounceOwnershipStartedEvent.OutputTuple,
      RenounceOwnershipStartedEvent.OutputObject
    >;

    "UniversalReceiver(address,uint256,bytes32,bytes,bytes)": TypedContractEvent<
      UniversalReceiverEvent.InputTuple,
      UniversalReceiverEvent.OutputTuple,
      UniversalReceiverEvent.OutputObject
    >;
    UniversalReceiver: TypedContractEvent<
      UniversalReceiverEvent.InputTuple,
      UniversalReceiverEvent.OutputTuple,
      UniversalReceiverEvent.OutputObject
    >;
  };
}
