/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockReentrantTokenSol from "./MockReentrantToken.sol";
export type { mockReentrantTokenSol };
